<?php
    $javascript ='';
    $cssScript = '<style>.widget .body{background:#fff;padding:0;}.widget{border:1px solid #ddd;}
    td:first-child { background:#eee}td:first-child + td { font-weight:bold;background:#fff;}background:#eee}td:first-child + td { font-weight:bold;background:#fff;}td:first-child + td + td { font-weight:bold;background:#eee;}td:first-child + td + td + td{ font-weight:bold;background:#fff;}#map_canvas {height: 400px;width: 100%;}.right{float:right;}</style>';
    $pageTitle = $this->translate('overview');
    $breadLinks = '<ul><li><a title="" href="'.$this->baseUrl ().'/'.$this->translate('lang').'/'.$this->controller.'/add"><i class="icos-add"></i><span>'.$this->translate('create').'</span><strong></strong></a></li></ul>';
	$content = $this->controller.'/'.$this->action.'.phtml';
    require_once TMP_USER_PATH;
?>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script> 
<?php  foreach ($this->siteView as $Values):?>
<div id="contentdata"> 
    <div class="wrapper">
        <div class="fluid">
            <div class="widget grid12">       
                <ul class="tabs">
                    <a class="buttonH bRed right" href="<?php echo  $this->url(array('Controller'=>'site','action'=>'index'));?>"><?php echo $this->translate('back')?></a>
                    <a title="" class="buttonH bBlue right" href="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/edit?actions=edit&&id=<?php echo $Values['site_Id']?>&&userids=<?php echo $Values['userid'];?>"><?php echo $this->translate('edit')?></a>
                    <li class="activeTab"><a href="#tabb1"><?php echo $this->translate('overview')?></a></li>
                    <li><a href="#tabb2">Organisme</a></li>                                       
                </ul>                
                <div class="tab_container">
                    <div class="tab_content" id="tabb1" style="display: block;">
                    <div class="widget justTable grid4">
                        <div class="body">
                        <table width="100%" cellspacing="0" cellpadding="0" class="tLight noBorderT">
                         <?php  $selected='selected'; ?>
                          <input type="hidden" name="hiddenID" value="<?php echo $Values['Com_Id'];?>" />
                            <tbody>
                                <tr>
                                    <td width="200"><?php echo $this->translate('sitename')?></td>
                                    <td width="600"><?php echo $Values['site_Name'];?></td>
                                </tr>
                                <tr>
                                    <td width="200">Description</td>
                                    <td width="600"><?php echo $Values['site_Description'];?></td>
                                </tr>
                                <tr>
                                   <td width="200"><?php echo $this->translate('companyaddress2')?></td>
                                   <td width="600"><?php echo $Values['site_Adresse1'];?></td>
                                </tr>
                                <tr>   
                                   <td width="200"><?php echo $this->translate('companyaddress2')?></td>
                                   <td width="600"><?php echo $Values['site_Adress2'];?></td> 
                                </tr>
                                <tr>
                                   <td width="200"><?php echo $this->translate('companycity')?></td>
                                    <td width="600"><?php echo $Values['site_City'];?></td>
                                </tr>
                                <tr>
                                    <td width="200"><?php echo $this->translate('companycodepostal')?></td>
                                    <td width="600"><?php echo $Values['site_Zipcode'];?></td> 
                               </tr>
                                <tr>     
                                    <td width="200"><?php echo $this->translate('companytype')?></td>
                                    <td width="600"><?php echo $Values['site_Type'];?></td>
                                    
                                    
                                </tr>
                                <tr>
                                    <td><?php echo $this->translate('companystatus')?></td>
                                    <td><?php
                                    if($Values['site_Statut']=='Actif')
                                    {
                                        $ClassStatut = 'label-success';
                                    }
                                    else if($Values['site_Statut']=='Suspendu')
                                    {
                                        $ClassStatut = 'label-warning';
                                    }
                                    else if($Values['site_Statut']=='Inactif')
                                    {
                                        $ClassStatut = 'label-important';
                                    }
                                    else
                                    {
                                       $ClassStatut = ''; 
                                    }
                                    ?><span class="label <?php echo $ClassStatut;?>"><?php echo $Values['site_Statut'];?></span></td>
                                 </tr>
                                <tr>   
                                    <td>Create date</td>
                                    <td><?php echo $Values['site_Createdate'];?></td>
                                    
                                </tr>
                            </tbody>
                        </table>
                        <?php endforeach;?>
                        </div>
                    </div> 
                    
                    <!-- Map -->
                    <div class="widget justTable grid4">
                        <div class="body" align="center">
                            <?php
                            /* for Convert accented characters to their plain ascii equivalents By Socheat Ngann */
                                    $normalizeChars = array(
                                        'Š'=>'S', 'š'=>'s', 'Ð'=>'Dj','Ž'=>'Z', 'ž'=>'z', 'À'=>'A', 'Á'=>'A', 'Â'=>'A', 'Ã'=>'A', 'Ä'=>'A',
                                        'Å'=>'A', 'Æ'=>'A', 'Ç'=>'C', 'È'=>'E', 'É'=>'E', 'Ê'=>'E', 'Ë'=>'E', 'Ì'=>'I', 'Í'=>'I', 'Î'=>'I',
                                        'Ï'=>'I', 'Ñ'=>'N', 'Ò'=>'O', 'Ó'=>'O', 'Ô'=>'O', 'Õ'=>'O', 'Ö'=>'O', 'Ø'=>'O', 'Ù'=>'U', 'Ú'=>'U',
                                        'Û'=>'U', 'Ü'=>'U', 'Ý'=>'Y', 'Þ'=>'B', 'ß'=>'Ss','à'=>'a', 'á'=>'a', 'â'=>'a', 'ã'=>'a', 'ä'=>'a',
                                        'å'=>'a', 'æ'=>'a', 'ç'=>'c', 'è'=>'e', 'é'=>'e', 'ê'=>'e', 'ë'=>'e', 'ì'=>'i', 'í'=>'i', 'î'=>'i',
                                        'ï'=>'i', 'ð'=>'o', 'ñ'=>'n', 'ò'=>'o', 'ó'=>'o', 'ô'=>'o', 'õ'=>'o', 'ö'=>'o', 'ø'=>'o', 'ù'=>'u',
                                        'ú'=>'u', 'û'=>'u', 'ý'=>'y', 'ý'=>'y', 'þ'=>'b', 'ÿ'=>'y', 'ƒ'=>'f'
                                    );
                                if($Values['site_Adresse1']!='')
                                {
                                            $address        = str_replace(" ","+",$Values['site_Adresse1']) . ",+" . str_replace(" ","+",$Values['site_Adress2']) . ",+" . str_replace(" ","+",$Values['site_City']) . ",+" . str_replace(" ","+",$Values['site_Zipcode']);
                                            $address        = strtr($address, $normalizeChars);
                                              /*Query Google Geocoding API */
                                            $ch = curl_init();
                                            curl_setopt($ch, CURLOPT_URL, "http://maps.googleapis.com/maps/api/geocode/xml?address=".$address."&sensor=false");
                                            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                                            $xml = curl_exec($ch);                                            
                                            
                                            //Use SimpleXML library to get the data from the XML string
                                            $xml = new SimpleXMLElement($xml);
                                            $lat = $xml->result[0]->geometry[0]->location[0]->lat;
                                            $lng = $xml->result[0]->geometry[0]->location[0]->lng;
                                            $coords = $lat . "," . $lng;
                                            curl_close($ch); //Close the CURL instance, to keep things tidy 
                                            if(!empty($lat))
                                            {
                           ?> 
                           <div id="map_canvas"></div>
                           <script type="text/javascript">
                            	function initialize() {
                                	var pos = new google.maps.LatLng(<?php echo $lat;?>, <?php echo $lng;?>);
                            		var centre = pos;
                            		var types = [google.maps.MapTypeId.ROADMAP,google.maps.MapTypeId.SATELLITE,google.maps.MapTypeId.HYBRID];
                                	var myOptions = { zoom: 14, center: centre, mapTypeId:google.maps.MapTypeId.ROADMAP, mapTypeControlOptions:{mapTypeIds: types}};
                                	var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
                            		
                            		var marker = new google.maps.Marker({position: pos, map: map, title:"IDEM"});
                            		var contentString = "<div id='map_infos'><?php echo $Values['site_Adresse1'];?></div>";
                            		var infowindow = new google.maps.InfoWindow({content: contentString});
                            		google.maps.event.addListener(marker, 'click', function() {infowindow.open(map,marker); });
                            		infowindow.open(map,marker);
                            	}
                            
                            </script> 
                            <?php
                                    }
                                }
                            ?>    
                        </div>
                    </div>    
                    <!-- end Map -->
                     <div class="widget justTable grid4">
                        <div class="body" align="center">
                            <img src="<?php echo $this->baseUrl ()?>/images/sitetest/00/01(1).gif" alt="" style="width: 100%; margin-bottom:30px" />
                            <a href="<?php echo $this->baseUrl ()?>/images/sitetest/00/01(5).jpg" class="lightbox" rel="group"><img src="<?php echo $this->baseUrl ()?>/images/sitetest/01(5).jpg" alt="" /></a>
                            <a href="<?php echo $this->baseUrl ()?>/images/sitetest/00/01(2).jpg" class="lightbox" rel="group" style="margin: 0 10px;"><img src="<?php echo $this->baseUrl ()?>/images/sitetest/01(2).jpg" alt="" /></a>
                            <a href="<?php echo $this->baseUrl ()?>/images/sitetest/00/01(3).jpg" class="lightbox" rel="group" style="margin-right: 10px;"><img src="<?php echo $this->baseUrl ()?>/images/sitetest/01(3).jpg" alt="" /></a>
                            <a href="<?php echo $this->baseUrl ()?>/images/sitetest/00/01(4).jpg" class="lightbox" rel="group"><img src="<?php echo $this->baseUrl ()?>/images/sitetest/01(4).jpg" alt="" /></a>
                        </div>
                    </div>
                    <!-- Photo Gallary -->
                    <!-- end Photo Gallary -->
                </div>
             <!-- end  formRow --> 
                    <div class="tab_content" id="tabb2" style="display: none;"> 
                        <div class="widget justTable grid6">
                        <div class="body">
                        <table width="100%" cellspacing="0" cellpadding="0" class="tLight noBorderT">
                        <?php  foreach ($this->siteView as $Values):?>
                         <?php  $selected='selected'; ?>
                          <input type="hidden" name="hiddenID" value="<?php echo $Values['Com_Id'];?>" />
                            <tbody>
                                <tr>
                                    <td width="200"><?php echo $this->translate('companyname')?></td>
                                    <td width="600"><?php echo $Values['Com_Name'];?></td>
                                </tr>
                                <tr>
                                    <td width="200"><?php echo $this->translate('RaisonSocial')?></td>
                                    <td width="600"><?php echo $Values['Com_RaisonSocial'];?></td>
                                </tr>
                                <tr>
                                   <td width="200"><?php echo $this->translate('companywebsite')?></td>
                                   <td width="600"><?php echo $Values['Com_Website'];?></td>
                                </tr>
                                <tr>   
                                   <td width="200"><?php echo $this->translate('companyemail')?></td>
                                   <td width="600"><?php echo $Values['Com_Mail'];?></td>
                                    
                                   
                                </tr>
                                <tr>
                                    <td width="200"><?php echo $this->translate('companycity')?></td>
                                    <td width="600"><?php echo $Values['Com_City'];?></td>
                                </tr>
                                <tr>    
                                    <td width="200"><?php echo $this->translate('companycountry')?></td>
                                    <td width="600"><?php echo $Values['Com_Country'];?></td>
                                    
                                    
                                </tr>
                                <tr>
                                   <td width="200"><?php echo $this->translate('companyaddress1')?></td>
                                    <td width="600"><?php echo $Values['Com_Address1'];?></td>
                               </tr>
                                <!--<tr>     
                                    <td width="200"><?php //echo $this->translate('companyaddress2')?></td>
                                    <td width="600"><?php //echo $Values['Com_Address2'];?></td>
                                </tr>-->
                                <tr>
                                    <td><?php echo $this->translate('companytelephone')?></td>
                                    <td><?php echo $Values['Com_Telephone'];?></td>
                                 </tr>
                                <tr>   
                                    <td><?php echo $this->translate('companyfax')?></td>
                                    <td><?php echo $Values['Com_Fax'];?></td>
                                    
                                </tr>
                            </tbody>
                        </table>
                        
                        </div>
                    </div>
                    
                    </div>

                </div>	
                <div class="clear"></div>		 
            </div>                
        </div>
    </div>
</div>
<?php endforeach;?>
