<?php
    $javascript ='';
    $cssScript = '';
    $pageTitle = 'Type Equipement';
    $cssScript = '<style>.formRow{padding: 5px 16px;}#main8 .widget{margin-top: 15px;}</style>';
	$content = $this->controller.'/'.$this->action.'.phtml';
    require_once TMP_USER_PATH;
?>

<div id="contentdata"> 
<div class="wrapper">
<div class="fluid">
            <form id="validate" class="main" method="post" action="<?php echo $this->url(array('controller','Typeequipement','action'=>'edit'));?>">
                <?php 
                  if(count($this->displayEditEquipement)!=0){
                    foreach ($this->displayEditEquipement as $rows){
                ?>
               
                <fieldset>
                    <div class="widget grid12">
                        <div class="whead"><h6><?php echo $this->translate('edittypeequipment')?></h6><div class="clear"></div></div>
                        <input type="hidden" name="editHidden" value="<?php echo $rows['Type_id'];?>"/>
                        <div class="formRow">
                            <div class="grid3"><label><?php echo $this->translate('typeequipmentname')?>:<span class="req">*</span></label></div>
                            <div class="grid9"><input type="text"  value="<?php echo $rows['Type_name'];?>" class="validate[required]" name="txttypename" id="txttypename"/></div><div class="clear"></div>
                        </div>
                        
                        <div class="formRow">
                            <div class="grid3"><label>Description:</label></div>
                            <div class="grid9"><input value="<?php echo $rows['Type_description'];?>" type="text" name="txttypedescription" id="txttypedescription"/></div><div class="clear"></div>
                        </div>
                        
                        <div class="formRow">
                            <div class="grid3"><label><?php echo $this->translate('reference')?>:<span class="req">*</span></label></div>
                            <div class="grid9">
                            
                            <select class="validate[required]" name="txtreference" id="txtreference">
                            	<option value="1">---- <?php echo $this->translate('selectone')?> ----</option>
                        <?php $selected='selected';?>
                        <?php 
							if(count($this->RefCode)!=0){
							 foreach($this->RefCode as $code){
				
						?>				
						<option <?php echo ($rows['Type_ref']==$code['ref_Code'])?$selected:''; ?> value="<?php echo $code['ref_Code'];?>"><?php echo $code['ref_code_lib'];?></option>
						<?php 
							}
						   }
						?>
                            </select></div><div class="clear"></div>
                        </div>
                        <div class="formRow">
                            <div class="grid3"><label><?php echo $this->translate('sitename')?>:<span class="req">*</span></label></div>
                            <div class="grid9">
                            <select class="validate[required]" name="txtisitename" id="txtisitename">
                            	<option value="1">---- <?php echo $this->translate('selectone')?> ----</option>
			                        <?php 
										if(count($this->siteName)!=0){
										 foreach($this->siteName as $getSiteName){
									?>				
									<option <?php echo ($rows['site_Id']==$getSiteName['site_Id'])?$selected:''; ?> value="<?php echo $getSiteName['site_Id'];?>"><?php echo $getSiteName['site_Name'];?></option>
									<?php 
										}
									   }
						?>
                            </select></div>
                            <div class="clear"></div>
                        </div>
                        
                        
                        
                         <div class="formRow">
                            <div class="grid3"><label><?php echo $this->translate('company')?>:<span class="req">*</span></label></div>
                            <div class="grid9"> 
                            <select class="validate[required]" name="txtcompanyname" id="txtcompanyname">
                            	<option value="1">---- <?php echo $this->translate('selectone')?> ----</option>
			                        <?php 
										if(count($this->CompanyName)!=0){
										 foreach($this->CompanyName as $getCompanyName){
									?>				
									<option <?php echo ($rows['Com_Id']==$getCompanyName['Com_Id'])?$selected:''; ?> value="<?php echo $getCompanyName['Com_Id'];?>"><?php echo $getCompanyName['Com_Name'];?></option>
									<?php 
										}
									   }
									?>
                            </select></div><div class="clear"></div>
                        </div>
                        
                        
                       <!--   <div id="uploader">You browser doesn't have HTML 4 support.</div>-->
                        <div class="formRow"><input type="submit" value="<?php echo $this->translate('update')?>"  name="BtnEdit" class="buttonM bBlue formSubmit" /><div class="clear"></div></div>
                        <div class="clear"></div>
                    </div>
                    
                      <!-- <div class="widget grid6">
                    	<div class="body" align="center">
                            <div style="max-height: 565px;overflow:hidden; margin-bottom:10px;">
                            <img src="<?php echo $this->baseUrl ()?>/images/sitetest/00/01(1).gif" alt="" style="width: 100%; margin-bottom:30px" />
                            </div>
                            <a href="<?php echo $this->baseUrl ()?>/images/sitetest/00/01(5).jpg" class="lightbox" rel="group"><img src="<?php echo $this->baseUrl ()?>/images/sitetest/01(5).jpg" alt="" /></a>
                            <a href="<?php echo $this->baseUrl ()?>/images/sitetest/00/01(2).jpg" class="lightbox" rel="group" style="margin: 0 10px;"><img src="<?php echo $this->baseUrl ()?>/images/sitetest/01(2).jpg" alt="" /></a>
                            <a href="<?php echo $this->baseUrl ()?>/images/sitetest/00/01(3).jpg" class="lightbox" rel="group" style="margin-right: 10px;"><img src="<?php echo $this->baseUrl ()?>/images/sitetest/01(3).jpg" alt="" /></a>
                            <a href="<?php echo $this->baseUrl ()?>/images/sitetest/00/01(4).jpg" class="lightbox" rel="group"><img src="<?php echo $this->baseUrl ()?>/images/sitetest/01(4).jpg" alt="" /></a>
                        </div>
                        
                    </div>-->
                </fieldset>
                <?php }}?>
            </form>
        </div>
		
	</div>
</div>