<?php
$javascript ='';
$cssScript = '<script type="text/javascript" src="'.$this->baseUrl ().'/theme/default/js/charts/jsapi.js"></script>
		<script type="text/javascript" src="'.$this->baseUrl ().'/theme/default/js/charts/jquery.gvChart-1.1.min.js"></script>';
$pageTitle = $this->translate('home');
$content = $this->controller.'/'.$this->action.'.phtml';
require_once TMP_USER_PATH;
?>
<!-- Content begins -->

	<!-- Main content -->
	<div class="wrapper">
		<!-- Chart -->
		<div class="fluid">               

                
                
                
			<div class="widget grid12">	
				<ul class="tabs">
					<li><a href="#tabb1"><?php echo $this->translate('myinteractid')?></a></li>
					<li><a href="#tabb2"><?php echo $this->translate('historical')?></a></li>
					<li><a href="#tabb3"><?php echo $this->translate('exportdestables')?></a></li>
				</ul>

				<div class="tab_container">
					<div id="tabb1" class="tab_content">
						<div class="fluid">
							<!-- Bars chart -->
							<div class="widget grid4 chartWrapper">
								<div class="whead hand opened" id="opened">
									<h6>Graphique d'intervention</h6>
									<div class="clear"></div>
								</div>
								<table id='myTable4'>
									<thead>
										<tr>
											<th></th>
											<th><?php echo $this->translate('controlvisuel')?></th>
											<th>Maintenance</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<th>2012</th>
											<td>35</td>
											<td>0</td>
										</tr>
										<tr>
											<th>2011</th>
											<td>0</td>
											<td>10</td>
										</tr>
									</tbody>
								</table>
							</div>

							<div class="widget grid4 chartWrapper">
								<div class="whead hand opened" id="opened">
									<h6>Graphique Equipement</h6>
									<div class="clear"></div>
								</div>
								<table id='myTable5'>
									<thead>
										<tr>
											<th></th>
											<th>Fontaines</th>
											<th>Tobaggan</th>
											<th>Balancoires</th>
											<th>Sante Plus</th>

										</tr>
									</thead>
									<tbody>
										<tr>
											<th>2010</th>
											<td>125</td>
											<td>185</td>
											<td>327</td>
											<td>400</td>
										</tr>
									</tbody>
								</table>
							</div>


							<!-- Donut -->
							<div class="widget grid4 chartWrapper">
								<div class="whead hand opened" id="opened">
									<h6>Vertican bars</h6>
									<div class="clear"></div>
								</div>
								<table id='myTable6'>
									<thead>
										<tr>
											<th></th>
											<th>Sites</th>

										</tr>
									</thead>
									<tbody>
										<tr>
											<th>2012</th>
											<td>35</td>

										</tr>
										<tr>
											<th>2011</th>
											<td>0</td>
										</tr>
									</tbody>
								</table>
							</div>


						</div>

						<div class="fluid">

							<!-- Bars chart -->
							<div style="display: none;">
								<div class="widget grid6 chartWrapper">
									<div class="whead hand opened" id="opened">
										<h6>Graphique Sites</h6>
										<div class="clear"></div>
									</div>
									<div class="body">
										<div class="bars" id="placeholder1_h"></div>
									</div>
								</div>


								<!-- Auto updating chart -->

								<div class="widget grid6 chartWrapper">
									<div class="whead hand opened" id="opened">
										<h6>Auto updating xxxxx</h6>
										<div class="clear"></div>
									</div>
									<div class="body">
										<div class="updating"></div>
									</div>
								</div>

							</div>
							<div class="clear"></div>

						</div>

					</div>



					<div id="tabb2" class="tab_content">


						<div class="widget">
							<div class="whead hand opened" id="opened">
								<h6>Fourisseur</h6>
								<div class="clear"></div>
							</div>
							<table cellpadding="0" cellspacing="0" width="100%"
								class="tDefault">
								<thead>
									<tr>
									
											 <td>N<sup>o</sup>Fournisseur</td>
											 <td>Raison sociale</td>
											 <td>Adresse1</td>
											 <td>CodePostal</td>
											 <td>Ville</td>
										 </tr>
								</thead>
								<tbody>
									<tr>
										<td>001</td>
										<td>SINEU GRAFF</td>
										<td>1 RUE DU PRESIDENT</td>
										<td>77186</td>
										<td>NOISIEL</td>
									</tr>
									<tr>
									    <td>002</td>
										<td>QUALI CITE</td>
										<td>PARC D ACTIVITE DU MOULLIN NEUF</td>
										<td>256130</td>	
										<td>PEAULE</td>
									</tr>
									<tr>
										<td>003</td>
										<td>BIKINI ET BERNUDA</td>
										<td>ZI DE LA VRAI CROIX</td>
										<td>56273</td>
										<td>PLOMEUR CESEX</td>
									
									</tr>
									<tr>
										<td>004</td>
										<td>KOMPAM</td>
										<td>363 RUE MARC SEGUIN</td>
										<td>77198</td>
										<td>DAMMARIE LES LYS</td>
									
									</tr>
									<tr>
										<td>005</td>
										<td>JMS</td>
										<td>39 RUE COROT</td>
										<td>77150</td>
										<td>LESIGNY</td>
									</tr>
								</tbody>
							</table>
						</div>




						<div class="widget">
							<div class="whead hand opened" id="opened">
								<h6>Type Equipement</h6>
								<div class="clear"></div>
							</div>
							<table cellpadding="0" cellspacing="0" width="100%"
								class="tDefault">
								<thead>
									<tr>
										<td>No type</td>
										<td>Nom</td>
										<td>Description</td>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>0001</td>
										<td>JEUX EXTERIEUES</td>
										<td></td>
									</tr>
								</tbody>
							</table>
						</div>




						<div class="widget">
							<div class="whead hand opened" id="opened">
								<h6>Equipement</h6>
								<div class="clear"></div>
							</div>
							<table cellpadding="0" cellspacing="0" width="100%"
								class="tDefault">
								<thead>
									<tr>
										<td>No Equip</td>
										<td>Nom</td>
										<td>Description</td>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>J001</td>
										<td>LE REMORQUEUR</td>
										<td>302</td>
									</tr>
									<tr>
										<td>J002</td>
										<td>TOBOGGEN</td>
										<td>MI 09 1006 02</td>
									</tr>
									<tr>
										<td>J003</td>
										<td>GRENOUILLE</td>
										<td>RE220</td>
									</tr>
									<tr>
										<td>J004</td>
										<td>CANARD</td>
										<td>RE236</td>
									</tr>
									<tr>
										<td>J005</td>
										<td>STRUCTURE</td>
										<td>M2511</td>

									</tr>
                                    <tr>
										<td>J006</td>
										<td>KANOE</td>
										<td>M151</td>

									</tr>
                                    <tr>
										<td>J007</td>
										<td>LA MOTO</td>
										<td>M113</td>

									</tr>
                                    <tr>
										<td>J008</td>
										<td>LA ROSE DES VENTS</td>
										<td>M142</td>

									</tr>
                                    <tr>
										<td>J009</td>
										<td>STRUCTURE</td>
										<td>3201126</td>

									</tr>
                                     <tr>
										<td>J0010</td>
										<td>VOITURE</td>
										<td>330458</td>

									</tr>
                                     <tr>
										<td>J0011</td>
										<td>STRUCTURE</td>
										<td>32040C</td>

									</tr>
                                     <tr>
										<td>J0012</td>
										<td>DOUBLE CHIEN</td>
										<td>330480</td>

									</tr>
								</tbody>
							</table>
						</div>

					</div>


					<div id="tabb3" class="tab_content">
						<a style="margin-left: 10px;" class="tablectrl_small bDefault" href="#"><span class="icos-download"></span> Export CSV</a>
						<a style="margin-left: 10px;" class="tablectrl_small bDefault" href="#"><span class="icos-download"></span> annuler</a>
          <div class="widget">
             <div class="whead"><span class="titleIcon check"><input type="checkbox" id="titleCheck" name="titleCheck" /></span><h6>Liste des tables</h6><div class="clear"></div></div>
             <table cellpadding="0" cellspacing="0" width="100%" class="tDefault checkAll check" id="checkAll">
               <tbody>
					 <tr>
                       <td>
                       <div class="whead"><span class="titleIcon check"><input type="checkbox" id="titleCheck" name="titleCheck" /></span><h6 style="display: block;float: left;font-size: 12px;font-weight: bold;
    padding: 8px 14px 7px;">Organisme</h6><div class="clear"></div></div>
    						<table cellpadding="0" cellspacing="0" width="100%" class="tDefault checkAll check" id="checkAll">
               <thead>
                   <tr>
                      
                       <td></td>
                        <td>N<sup>o</sup>Ref</td>
					    <td>Raison Sociale</td>
						<td>Ville</td>
                   </tr>
               </thead>
               <tbody>
                   <tr>
                       
                       <td></td>
                       <td>0001</td>
                       <td>SAN Vai Maubuee</td>
                       <td>Torcy</td>
                   </tr>
                   <tr>
                       
                       <td></td>
                       <td>0002</td>
                       <td>SAN Caergy Pontoise</td>
                       <td>Cergy Pontoise</td>
                   </tr>
                   <tr>
                      
                       <td></td>
                       <td>0003</td>
                       <td>SAN Vai D'Europe</td>
                       <td>Marne-la-Vallee</td>
                   </tr>   
               </tbody>
             </table>
             </td>   
         </tr>       
               </tbody>
             </table>
           
         </div>
         <div class="widget">
         <div class="whead"><span class="titleIcon check"><input type="checkbox" id="titleCheck" name="titleCheck" /></span><h6>Fournisseur</h6><div class="clear"></div></div>
             <table cellpadding="0" cellspacing="0" width="100%" class="tDefault checkAll check" id="checkAll">
               <thead>
                   <tr>
                      
                       <td></td>
                        <td>N<sup>o</sup>Ref</td>
					    <td>Raison Sociale</td>
						<td>Ville</td>
                   </tr>
               </thead>
               <tbody>
                   <tr>
                       
                       <td></td>
                       <td>0001</td>
                       <td>SAN Vai Maubuee</td>
                       <td>Torcy</td>
                   </tr>
                   <tr>
                       
                       <td></td>
                       <td>0002</td>
                       <td>SAN Caergy Pontoise</td>
                       <td>Cergy Pontoise</td>
                   </tr>
                   <tr>
                      
                       <td></td>
                       <td>0003</td>
                       <td>SAN Vai D'Europe</td>
                       <td>Marne-la-Vallee</td>
                   </tr>   
               
               </tbody>
             </table>
           
         </div>
		 <div class="widget">
         <div class="whead"><span class="titleIcon check"><input type="checkbox" id="titleCheck" name="titleCheck" /></span><h6>Site</h6><div class="clear"></div></div>
             <table cellpadding="0" cellspacing="0" width="100%" class="tDefault checkAll check" id="checkAll">
               <thead>
                   <tr>
                      
                       <td></td>
                        <td>N<sup>o</sup>Ref</td>
					    <td>Nom</td>
						<td>Ville</td>
                   </tr>
               </thead>
               <tbody>
                   <tr>
                       
                       <td></td>
                       <td>0001</td>
                       <td>SAN Vai Maubuee</td>
                       <td>Torcy</td>
                   </tr>
                   <tr>
                       
                       <td></td>
                       <td>0002</td>
                       <td>SAN Caergy Pontoise</td>
                       <td>Cergy Pontoise</td>
                   </tr>
                   <tr>
                      
                       <td></td>
                       <td>0003</td>
                       <td>SAN Vai D'Europe</td>
                       <td>Marne-la-Vallee</td>
                   </tr>   
               
               </tbody>
             </table>
         </div>
		 <div class="widget">
         <div class="whead"><span class="titleIcon check"><input type="checkbox" id="titleCheck" name="titleCheck" /></span><h6>Typ d'equipement</h6><div class="clear"></div></div>
             <table cellpadding="0" cellspacing="0" width="100%" class="tDefault checkAll check" id="checkAll">
               <thead>
                   <tr>
                      
                       <td></td>
                        <td>N<sup>o</sup>Ref</td>
					    <td>Nom</td>
						<td>Description</td>
                   </tr>
               </thead>
               <tbody>
                   <tr>
                       
                       <td></td>
                       <td>0001</td>
                       <td>SAN Vai Maubuee</td>
                       <td>Torcy</td>
                   </tr>
                   <tr>
                       
                       <td></td>
                       <td>0002</td>
                       <td>SAN Caergy Pontoise</td>
                       <td>Cergy Pontoise</td>
                   </tr>
                   <tr>
                      
                       <td></td>
                       <td>0003</td>
                       <td>SAN Vai D'Europe</td>
                       <td>Marne-la-Vallee</td>
                   </tr>   
               
               </tbody>
             </table>
         </div>
		 <div class="widget">
         <div class="whead"><span class="titleIcon check"><input type="checkbox" id="titleCheck" name="titleCheck" /></span><h6>Equipement</h6><div class="clear"></div></div>
             <table cellpadding="0" cellspacing="0" width="100%" class="tDefault checkAll check" id="checkAll">
               <thead>
                   <tr>
                       <td></td>
                        <td>No Equip</td>
					    <td>Nom</td>
						<td>Description</td>
                   </tr>
					   </thead>
					   <tbody>
                   <tr>
										<td></td>
										<td>J001</td>
										<td>LE REMORQUEUR</td>
										<td>302</td>
									</tr>
									<tr>
									    <td></td>
										<td>J002</td>
										<td>TOBOGGEN</td>
										<td>MI 09 1006 02</td>
									</tr>
									<tr>
									    <td></td>
										<td>J003</td>
										<td>GRENOUILLE</td>
										<td>RE220</td>
									</tr>
									<tr>
									    <td></td>
										<td>J004</td>
										<td>CANARD</td>
										<td>RE236</td>
									</tr>
									<tr>
									    <td></td>
										<td>J005</td>
										<td>STRUCTURE</td>
										<td>M2511</td>

									</tr>
                                    <tr>
									    <td></td>
										<td>J006</td>
										<td>KANOE</td>
										<td>M151</td>

									</tr>
                                    <tr>
									    <td></td>
										<td>J007</td>
										<td>LA MOTO</td>
										<td>M113</td>

									</tr>
                                    <tr>
									    <td></td>
										<td>J008</td>
										<td>LA ROSE DES VENTS</td>
										<td>M142</td>

									</tr>
                                    <tr>
									    <td></td>
										<td>J009</td>
										<td>STRUCTURE</td>
										<td>3201126</td>

									</tr>
                                     <tr>
									    <td></td>
										<td>J0010</td>
										<td>VOITURE</td>
										<td>330458</td>

									</tr>
                                     <tr>
									    <td></td>
										<td>J0011</td>
										<td>STRUCTURE</td>
										<td>32040C</td>

									</tr>
                                     <tr>
									    <td></td>
										<td>J0012</td>
										<td>DOUBLE CHIEN</td>
										<td>330480</td>
									</tr>  
               </tbody>
             </table>
         </div>
		 <br/>
         <a style="margin-left: 10px;" class="tablectrl_small bDefault" href="#"></span> Export CSV</a>
        <a style="margin-left: 10px;" class="tablectrl_small bDefault" href="#"></span> annuler</a>
	
     </div>
  </div>
	
				<div class="clear"></div>
			</div>

		</div>




		<div class="widget">
			<div class="whead">
				<h6><?php echo $this->translate('myinterventions')?></h6>
				<div class="clear"></div>
			</div>
			<table cellpadding="0" cellspacing="0" width="100%"
				class="tDefault checkAll tMedia" id="checkAll">
				<thead>
					<tr>
						<td>Close</td>
						<td>Organisme</td>
						<td><?php echo $this->translate('city')?></td>
						<td>Sites</td>
						<td>Equipement</td>
						<td><?php echo $this->translate('startdate')?></td>
						<td style="width:85px;"><?php echo $this->translate('accept')?></td>
						<td style="width:70px;">Action</td>

					</tr>
				</thead>
				<tfoot>
					<tr>
						<td colspan="8">

							<div class="tPages">
								<ul class="pages">
									<li class="prev"><a href="#" title=""><span
											class="icon-arrow-14"></span></a></li>
									<li><a href="#" title="" class="active">1 </a></li>
									<li><a href="#" title="">2 </a></li>
									<li><a href="#" title="">3 </a></li>
									<li><a href="#" title="">4 </a></li>
									<li>...</li>
									<li><a href="#" title="">20 </a></li>
									<li class="next"><a href="#" title=""><span
											class="icon-arrow-17"></span></a></li>
								</ul>
							</div>
						</td>
					</tr>
				</tfoot>
				<tbody>
					<tr>
						<td><a href="#" class="tablectrl_small bDefault tipS"
							title="Close"><span class="iconb" data-icon="&#xe136;"></span></a></td>
						<td>San Vai Maubuee</td>
						<td>Champs Sur Marne</td>
						<td>Bois De Grace N1</td>
						<td>Balancoires</td>
						<td>08/03/2012 11:30am</td>
						<td class="tableActs">
							<ul class="btn-group toolbar">
                                <li><a href="#" class="tablectrl_small bDefault tipS" data-toggle="dropdown"  title="Options"><span class="iconb" data-icon="&#xe1f7;"></span></a>
                                    <ul class="dropdown-menu pull-right">
		                                <li><a href="#"><span class="iconb" data-icon="&#xe097;" title="Accept"></span>&nbsp;&nbsp;Accept</a></li>
		                                <li><a href="#"><span class="iconb" data-icon="&#xe217;" title="Pending"></span>&nbsp;&nbsp;Pending</a></li>
		                                <li><a href="#"><span class="iconb" data-icon="&#xe093;" title="Deny"></span>&nbsp;&nbsp;Deny</a></li>                                       
                                    </ul>
                                </li>
                                
                            </ul>
						</td>
						<td class="tableActs">
							<ul class="btn-group toolbar">
                                <li><a href="#" class="tablectrl_small bDefault tipS" data-toggle="dropdown"  title="Options"><span class="iconb" data-icon="&#xe1f7;"></span></a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="#"><span class="iconb" data-icon="&#xe1db;" title="Edit"></span>&nbsp;&nbsp;Edit</a></li>
                                        <li><a href="#"><span class="iconb" data-icon="&#xe1ba;" title="View"></span>&nbsp;&nbsp;View</a></li>                                        
                                    </ul>
                                </li>
                            </ul>
						</td>

					</tr>
					<tr>
						<td><a href="#" class="tablectrl_small bDefault tipS"
							title="Close"><span class="iconb" data-icon="&#xe136;"></span></a></td>
						<td></td>
						<td>Noisel</td>
						<td>Pc De Noisiel N2</td>
						<td>Le remorqueur</td>
						<td>08/03/2012 10:30am</td>
						<td class="tableActs">
							<ul class="btn-group toolbar">
                                <li><a href="#" class="tablectrl_small bDefault tipS" data-toggle="dropdown"  title="Options"><span class="iconb" data-icon="&#xe1f7;"></span></a>
                                    <ul class="dropdown-menu pull-right">
		                                <li><a href="#"><span class="iconb" data-icon="&#xe097;" title="Accept"></span>&nbsp;&nbsp;Accept</a></li>
		                                <li><a href="#"><span class="iconb" data-icon="&#xe217;" title="Pending"></span>&nbsp;&nbsp;Pending</a></li>
		                                <li><a href="#"><span class="iconb" data-icon="&#xe093;" title="Deny"></span>&nbsp;&nbsp;Deny</a></li>                                       
                                    </ul>
                                </li>
                            </ul>
						</td>
						<td class="tableActs">
							<ul class="btn-group toolbar">
                                <li><a href="#" class="tablectrl_small bDefault tipS" data-toggle="dropdown"  title="Options"><span class="iconb" data-icon="&#xe1f7;"></span></a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="#"><span class="iconb" data-icon="&#xe1db;" title="Edit"></span>&nbsp;&nbsp;Edit</a></li>
                                        <li><a href="#"><span class="iconb" data-icon="&#xe1ba;" title="View"></span>&nbsp;&nbsp;View</a></li>                                        
                                    </ul>
                                </li>
                            </ul>
						</td>

					</tr>
					<tr>
						<td><a href="#" class="tablectrl_small bDefault tipS"
							title="Close"><span class="iconb" data-icon="&#xe136;"></span></a></td>
						<td></td>
						<td>Champs Sur Marne</td>
						<td>Bois Du Luzard N2</td>
						<td></td>
						<td>08/03/2012 09:30am</td>
						<td class="tableActs">
							<ul class="btn-group toolbar">
                                <li><a href="#" class="tablectrl_small bDefault tipS" data-toggle="dropdown"  title="Options"><span class="iconb" data-icon="&#xe1f7;"></span></a>
                                    <ul class="dropdown-menu pull-right">
		                                <li><a href="#"><span class="iconb" data-icon="&#xe097;" title="Accept"></span>&nbsp;&nbsp;Accept</a></li>
		                                <li><a href="#"><span class="iconb" data-icon="&#xe217;" title="Pending"></span>&nbsp;&nbsp;Pending</a></li>
		                                <li><a href="#"><span class="iconb" data-icon="&#xe093;" title="Deny"></span>&nbsp;&nbsp;Deny</a></li>                                       
                                    </ul>
                                </li>
                            </ul>
						</td>
						<td class="tableActs">
							<ul class="btn-group toolbar">
                                <li><a href="#" class="tablectrl_small bDefault tipS" data-toggle="dropdown"  title="Options"><span class="iconb" data-icon="&#xe1f7;"></span></a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="#"><span class="iconb" data-icon="&#xe1db;" title="Edit"></span>&nbsp;&nbsp;Edit</a></li>
                                        <li><a href="#"><span class="iconb" data-icon="&#xe1ba;" title="View"></span>&nbsp;&nbsp;View</a></li>                                        
                                    </ul>
                                </li>
                            </ul>
						</td>

					</tr>
					<tr>
						<td><a href="#" class="tablectrl_small bDefault tipS"
							title="Close"><span class="iconb" data-icon="&#xe136;"></span></a></td>
						<td></td>
						<td>Lognes</td>
						<td>Square Rousseau N1</td>
						<td></td>
						<td>08/03/2012 08:30am</td>
						<td class="tableActs">
							<ul class="btn-group toolbar">
                                <li><a href="#" class="tablectrl_small bDefault tipS" data-toggle="dropdown"  title="Options"><span class="iconb" data-icon="&#xe1f7;"></span></a>
                                    <ul class="dropdown-menu pull-right">
		                                <li><a href="#"><span class="iconb" data-icon="&#xe097;" title="Accept"></span>&nbsp;&nbsp;Accept</a></li>
		                                <li><a href="#"><span class="iconb" data-icon="&#xe217;" title="Pending"></span>&nbsp;&nbsp;Pending</a></li>
		                                <li><a href="#"><span class="iconb" data-icon="&#xe093;" title="Deny"></span>&nbsp;&nbsp;Deny</a></li>                                       
                                    </ul>
                                </li>
                            </ul>
						</td>
						<td class="tableActs">
							<ul class="btn-group toolbar">
                                <li><a href="#" class="tablectrl_small bDefault tipS" data-toggle="dropdown"  title="Options"><span class="iconb" data-icon="&#xe1f7;"></span></a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="#"><span class="iconb" data-icon="&#xe1db;" title="Edit"></span>&nbsp;&nbsp;Edit</a></li>
                                        <li><a href="#"><span class="iconb" data-icon="&#xe1ba;" title="View"></span>&nbsp;&nbsp;View</a></li>                                        
                                    </ul>
                                </li>
                            </ul>
						</td>

					</tr>

				</tbody>
			</table>
		</div>

		<!-- My Activity Stream-->
		<div class="fluid">

			<!-- Messages #1 -->
			<!--<div class="widget grid12" style="height: 380px; overflow: scroll;">
				<div class="whead">
					<h6><?php /*?><?php echo $this->translate('myactivitystream')?><?php */?></h6>

					<div class="clear"></div>
				</div>

				<ul class="messagesOne">

					<li><textarea rows="2" cols="" name="textarea" class="auto"
							placeholder="Write your message"></textarea> <input type="submit"
						name="sendMessage" class="buttonM bLightBlue" value="Post" /></li>
					<li class="divider"><span></span></li>

					<li class="by_user"><a href="#" title=""><img
							src="<?php /*?><?php echo $this->baseUrl();?><?php */?>/images/live/face1.png" alt="" /></a>
						<div class="messageArea">
							<span class="aro"></span>
							<div class="infoRow">
								<span class="name"><strong>John </strong> says: </span> <span
									class="time">3 hours xxx </span>
								<div class="clear"></div>
							</div>
							Lorem xxxxx dolor sit xxxx, consectetur adipiscing xxxx. Nam vel
							xxx enim, vel xxxxxxxx felis. Ut xxxxxxxx, leo eget xxxxxxx
							scelerisque, eros xxxxx lacinia velit, xxx rhoncus mi xxx
							eleifend orci. Phasellus ut xxx urna, id xxxxxx libero. Nulla
							xxxx arcu vel xxxxx suscipit ultricies xx id velit
						</div>
						<div class="clear"></div></li>
					<li class="divider"><span></span></li>

					<li class="by_me"><a href="#" title=""><img
							src="<?php /*?><?php echo $this->baseUrl();?><?php */?>/images/live/face2.png" alt="" /></a>
						<div class="messageArea">
							<span class="aro"></span>
							<div class="infoRow">
								<span class="name"><strong>Eugene </strong> says: </span> <span
									class="time">3 hours xxx </span>
								<div class="clear"></div>
							</div>
							Lorem xxxxx dolor sit xxxx, consectetur adipiscing xxxx. Nam vel
							xxx enim, vel xxxxxxxx felis. Ut xxxxxxxx, leo eget xxxxxxx
							scelerisque, eros xxxxx lacinia velit, xxx rhoncus mi xxx
							eleifend orci. Phasellus ut xxx urna, id xxxxxx libero. Nulla
							xxxx arcu vel xxxxx suscipit ultricies xx id velit
						</div>
						<div class="clear"></div></li>

					<li class="by_me"><a href="#" title=""><img
							src="<?php /*?><?php echo $this->baseUrl();?><?php */?>/images/live/face2.png" alt="" /></a>
						<div class="messageArea">
							<span class="aro"></span>
							<div class="infoRow">
								<span class="name"><strong>Eugene </strong> says: </span> <span
									class="time">3 hours xxx </span>
								<div class="clear"></div>
							</div>
							Lorem xxxxx dolor sit xxxx, consectetur adipiscing xxxx. Nam vel
							xxx enim, vel xxxxxxxx felis. Ut xxxxxxxx, leo eget xxxxxxx
							scelerisque, eros xxxxx lacinia velit, xxx rhoncus mi xxx
							eleifend orci. Phasellus ut xxx urna, id xxxxxx libero. Nulla
							xxxx arcu vel xxxxx suscipit ultricies xx id velit
						</div>
						<div class="clear"></div></li>

					<li class="divider"><span></span></li>


					<li class="by_me"><a href="#" title=""><img
							src="<?php /*?><?php echo $this->baseUrl();?><?php */?>/images/live/face2.png" alt="" /></a>
						<div class="messageArea">
							<span class="aro"></span>
							<div class="infoRow">
								<span class="name"><strong>Eugene </strong> says: </span> <span
									class="time">3 hours xxx </span>
								<div class="clear"></div>
							</div>
							Lorem xxxxx dolor sit xxxx, consectetur adipiscing xxxx. Nam vel
							xxx enim, vel xxxxxxxx felis. Ut xxxxxxxx, leo eget xxxxxxx
							scelerisque, eros xxxxx lacinia velit, xxx rhoncus mi xxx
							eleifend orci. Phasellus ut xxx urna, id xxxxxx libero. Nulla
							xxxx arcu vel xxxxx suscipit ultricies xx id velit
						</div>
						<div class="clear"></div></li>
				</ul>
			</div>


		</div>-->





	</div>
	<!-- Main content ends -->
<script type="text/javascript">
		gvChartInit();
		jQuery(document).ready(function(){
			jQuery('#myTable4').gvChart({
				chartType: 'ColumnChart',
				gvSettings: {
					vAxis: {title: "nombre d'interventions"},
					hAxis: {title: ''},
					width: '100%',
					height: 300
					}
			});
			
				jQuery('#myTable6').gvChart({
				chartType: 'ColumnChart',
				gvSettings: {
					vAxis: {title: "nombre Site"},
					hAxis: {title: ''},
					width: '100%',
					height: 300
					}
			});
			
			jQuery('#myTable5').gvChart({
				chartType: 'PieChart',
				gvSettings: {
					vAxis: {title: 'No of players'},
					hAxis: {title: 'Month'},
					width: '100%',
					height: 300
					}
			});
		});
		</script>
<!-- Content ends -->