<?php
    $javascript ='';
    $cssScript = '';
    $pageTitle = $this->translate('edit');
    $cssScript = '<style>.formRow{padding: 5px 16px;}#main12 .widget{margin-top: 15px;}</style>';
	$content = $this->controller.'/'.$this->action.'.phtml';
    require_once TMP_USER_PATH;
?>
<div id="contentdata">

<?php 
    if(count($this->getEditFactory )!=0):
    foreach($this->getEditFactory as $getFactory):
    $selected='selected';
?>
<form name="registerForm" onsubmit="return validateForm()" enctype="multipart/form-data" id="usualValidate" class="main" method="post" action="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/editfactory">
	<div class="wrapper">
	
	<div class="fluid">
                <div class="widget grid12">       
                    <ul class="tabs">
                        <li><a href="#tabb1"><?php echo $this->translate('companytab1')?></a></li>
                        <li><a href="#tabb2"><?php echo $this->translate('companytab2')?></a></li>
                    </ul>
                    
                    <div class="tab_container">
                        <div id="tabb1" class="tab_content">
                            <div id="main12">
                    <!-- main grid8 -->
					<div class="grid12">                        
                            <!-- form inside -->
                            <div class="formRow fluid">
                                <!-- form create -->
                                <div class="widget grid6">
                                    <div class="body">
                                        <input type="hidden" name="hiddenID" value="<?php echo $getFactory['Fou_Id'];?>" />
                                      <div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companyname')?>:<span class="req">*</span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $getFactory['Fou_Name'];?>" name="fac_name"  id="fac_name" class="required"/>
            							</div>							
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('RaisonSocial')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $getFactory['Fou_RaisonSocial'];?>" name="fac_social" id="fac_social" />
            							</div>
            						<div class="clear"></div>
            						</div>
            						 <div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companylogo') ?>:</label>
            							</div>
            							<div class="grid8">
            								<input type="file" id="logo" name="fileupload" class="logo"
            									size="18.5" style="opacity: 0;"/>
            							</div>
            							<div class="clear"></div>
            						</div> 
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companyaddress1')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<div id="addresss"><textarea rows="3" cols="50"  name="fac_address1" id="fac_address1" placeholder="<?php echo $this->translate('selectmap')?>"><?php echo $getFactory['Fou_Adresse1'];?></textarea></div>
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companycodepostal')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $getFactory['Fou_ZipCode'];?>" name="fac_zipcode" id="fac_zipcode" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companycity')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<div id="states"><input type="text" value="<?php echo $getFactory['Fou_City'];?>" name="fac_city" id="fac_city" /></div>
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companycountry')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<select name="fac_country" id="fac_country" >
            									<!-- <option value="">-- <?php //echo $this->translate('selectcountry')?> --</option> -->
            									<option value="France">France</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='France')?$selected:'' ;?>
                										value="France">France</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='France, Metropolitan')?$selected:'' ;?>
                										value="France, Metropolitan">France, Metropolitan</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='French Guiana')?$selected:'' ;?>
                										value="French Guiana">French Guiana</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='French Polynesia')?$selected:'' ;?>
                										value="French Polynesia">French Polynesia</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='French Southern Territories')?$selected:'' ;?>
                										value="French Southern Territories">French SouthernTerritories</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='Germany')?$selected:'' ;?>
                										value="Germany">Germany</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='Italy')?$selected:'' ;?>
                										value="Italy">Italy</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='New Zealand')?$selected:'' ;?>
                										value="New Zealand">New Zealand</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='Portugal')?$selected:'' ;?>
                										value="Portugal">Portugal</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='Sweden')?$selected:'' ;?>
                										value="Sweden">Sweden</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='Switzerland')?$selected:'' ;?>
                										value="Switzerland">Switzerland</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='Turkey')?$selected:'' ;?>
                										value="Turkey">Turkey</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='United Kingdom')?$selected:'' ;?>
                										value="United Kingdom">United Kingdom</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='United States')?$selected:'' ;?>
                										value="United States">United States</option>
                									<option
                										<?php echo ($getFactory['Fou_Country']=='United States Minor Outlying Islands')?$selected:'' ;?>
                										value="United States Minor Outlying Islands">United States
                										Minor Outlying Islands</option>
            								</select>
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companytelephone')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $getFactory['Fou_Telephone'];?>" name="fac_telephone" id="fac_telephone" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companyfax')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $getFactory['Fou_Fax'];?>" name="fac_fax" id="fac_fax" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            						<div class="grid4">
            								<label><?php echo $this->translate('companyemail')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $getFactory['Fou_Mail'];?>" name="fac_mail" id="fac_mail" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						 <div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companywebsite')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $getFactory['Fou_Website'];?>" name="fac_website" id="fac_website" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
                          </div>
                   </div>
                
                               
                                <!--The end grid 6-->
                                <div class="widget grid6">
                                 <center><p style="font:bolder;" ><?php echo $this->translate('selectmap')?></p></center>
                                    <div class="body">
                                        <style>
                            		.map {
                            			height: 435px;
                            			width: 100%;
                            		}
                            		.ui-dialog
                            		{
                            			background:#fff;
                            			border:1px solid #ddd;
                            			padding:5px;
                            		}
                            		.ui-dialog-content {height:10px!important;}
                            		</style>
                                    <script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/modernizr.min.js"></script>
                                    <div id="map_canvas" class="map rounded"></div>
                                    <div id="dialog"></div>
                                    
                                    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>  
                                                               		
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/underscore-1.2.2/underscore.min.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/backbone-0.5.3/backbone.min.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/prettify/prettify.min.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/demo.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/jquery.ui.map.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/jquery.ui.map.services.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/jquery.ui.map.extensions.js"></script>
                            		<script type="text/javascript">
                                    <?PHP                                 
                                    /* for Convert accented characters to their plain ascii equivalents By Socheat Ngann */
                                    $normalizeChars = array(
                                        'Š'=>'S', 'š'=>'s', 'Ð'=>'Dj','Ž'=>'Z', 'ž'=>'z', 'À'=>'A', 'Á'=>'A', 'Â'=>'A', 'Ã'=>'A', 'Ä'=>'A',
                                        'Å'=>'A', 'Æ'=>'A', 'Ç'=>'C', 'È'=>'E', 'É'=>'E', 'Ê'=>'E', 'Ë'=>'E', 'Ì'=>'I', 'Í'=>'I', 'Î'=>'I',
                                        'Ï'=>'I', 'Ñ'=>'N', 'Ò'=>'O', 'Ó'=>'O', 'Ô'=>'O', 'Õ'=>'O', 'Ö'=>'O', 'Ø'=>'O', 'Ù'=>'U', 'Ú'=>'U',
                                        'Û'=>'U', 'Ü'=>'U', 'Ý'=>'Y', 'Þ'=>'B', 'ß'=>'Ss','à'=>'a', 'á'=>'a', 'â'=>'a', 'ã'=>'a', 'ä'=>'a',
                                        'å'=>'a', 'æ'=>'a', 'ç'=>'c', 'è'=>'e', 'é'=>'e', 'ê'=>'e', 'ë'=>'e', 'ì'=>'i', 'í'=>'i', 'î'=>'i',
                                        'ï'=>'i', 'ð'=>'o', 'ñ'=>'n', 'ò'=>'o', 'ó'=>'o', 'ô'=>'o', 'õ'=>'o', 'ö'=>'o', 'ø'=>'o', 'ù'=>'u',
                                        'ú'=>'u', 'û'=>'u', 'ý'=>'y', 'ý'=>'y', 'þ'=>'b', 'ÿ'=>'y', 'ƒ'=>'f'
                                    );                                   
                                        if($getFactory['Fou_Adresse1']!='')
                                        {                                            
                                            //$address    = str_replace(' ', '%20', $Values['Com_City'].', '.$Values['Com_Address1']);
                                            $address    = str_replace(" ","+",$getFactory['Fou_Adresse1']) . ",+" . str_replace(" ","+",$getFactory['Fou_City']) . ",+" . str_replace(" ","+",$getFactory['Fou_Country']);
                                            $address    = strtr($address, $normalizeChars);
                                              /*Query Google Geocoding API */
                                            $ch = curl_init();
                                            curl_setopt($ch, CURLOPT_URL, "http://maps.googleapis.com/maps/api/geocode/xml?address=".$address."&sensor=false");
                                            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                                            $xml = curl_exec($ch);                                                                                        
                                            
                                            //Use SimpleXML library to get the data from the XML string
                                            $xml = new SimpleXMLElement($xml);
                                            $lat = $xml->result[0]->geometry[0]->location[0]->lat;
                                            $lng = $xml->result[0]->geometry[0]->location[0]->lng;
                                            $coords = $lat . "," . $lng;
                                            curl_close($ch); //Close the CURL instance, to keep things tidy  
                                            
                                    }else
                                        {
                                            $client  = @$_SERVER['HTTP_CLIENT_IP'];
                                            $forward = @$_SERVER['HTTP_X_FORWARDED_FOR'];
                                            $remote  = $_SERVER['REMOTE_ADDR'];
                                            $result  = "France";
                                            if(filter_var($client, FILTER_VALIDATE_IP))
                                            {
                                                $ip = $client;
                                            }
                                            elseif(filter_var($forward, FILTER_VALIDATE_IP))
                                            {
                                                $ip = $forward;
                                            }
                                            else
                                            {
                                                $ip = $remote;
                                            }
                                        
                                            $ip_data = @json_decode(file_get_contents("http://www.geoplugin.net/json.gp?ip=".$ip));
                                        
                                            if($ip_data && $ip_data->geoplugin_countryName != null)
                                            {
                                                $result = $ip_data->geoplugin_countryName;
                                            }
                                            else 
                                            {
                                                $result;
                                            }
                                        $address    = str_replace(" ","+",$result);
                                        $address        = strtr($address, $normalizeChars);
                                              /*Query Google Geocoding API */
                                            $ch = curl_init();
                                            curl_setopt($ch, CURLOPT_URL, "http://maps.googleapis.com/maps/api/geocode/xml?address=".$address."&sensor=false");
                                            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                                            $xml = curl_exec($ch);                                            
                                            
                                            //Use SimpleXML library to get the data from the XML string
                                            $xml = new SimpleXMLElement($xml);
                                            $lat = $xml->result[0]->geometry[0]->location[0]->lat;
                                            $lng = $xml->result[0]->geometry[0]->location[0]->lng;
                                            $coords = $lat . "," . $lng;
                                            curl_close($ch); //Close the CURL instance, to keep things tidy
                                        }                                            
                                        ?>
                                        var mobileDemo = { 'center': '<?php echo $lat;?>,<?php echo $lng;?>', 'zoom': 10 };                                    
                            				demo.add(function() {
                            					$('#map_canvas').gmap({'center': mobileDemo.center, 'zoom': mobileDemo.zoom, 'disableDefaultUI':true, 'callback': function(map) {
                            						var self = this;
                            						self.set('openDialog', function(marker) {
                            							$('#dialog'+marker.__gm_id).dialog({'modal':true, 'title': 'Edit and save point', 'buttons': { 
                            								'No': function() { $(this).dialog('close'); marker.setMap(null); return false; },
                            								'Save': function() { $(this).dialog('close'); return false; }
                            							}});
                            						});
                            						self.set('findLocation', function(location, marker) {
                            							self.search({'location': location}, function(results, status) {
                            								if ( status === 'OK' ) {
                            									$.each(results[0].address_components, function(i,v) {
                            										if ( v.types[0] == "administrative_area_level_1" || v.types[0] == "administrative_area_level_2" ) {
                            											$('#state'+marker.__gm_id).val(v.long_name);
                            										} else if ( v.types[0] == "country") {
                            											$('#country'+marker.__gm_id).val(v.long_name);
                            										}
                            									});
                            									marker.setTitle(results[0].formatted_address);
                            									$('#address'+marker.__gm_id).val(results[0].formatted_address);
                            									self.get('openDialog')(marker);
                            								}
                            							});
                            						});
                            						$(map).click( function(event) {
                            							self.addMarker({'position': event.latLng, 'draggable': true, 'bounds': false}, function(map, marker) {
                            								$('#states').html('<input type="text" id="state'+marker.__gm_id+'" class="txt" name="fac_city" value=""/>');
                            								$('#addresss').html('<textarea rows="3" cols="50" id="address'+marker.__gm_id+'" class="txt" name="fac_address1" ></textarea>');
                            								$('#dialog').append('<form id="dialog'+marker.__gm_id+'" method="get" action="/" style="display:none;">Do you want to save?</form>');
                            								self.get('findLocation')(marker.getPosition(), marker);
                            							}).dragend( function(event) {
                            								self.get('findLocation')(event.latLng, this);
                            							}).click( function() {
                            								self.get('openDialog')(this);
                            							})
                            						});
                            					}});
                            				}).load(); 
                                                                                 	
                                    </script> 
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <div class="formRow fluid"><div class="clear"></div> </div>
                                 
                            </div>
                    </div>
                </div>            
    </div>
                        
                        
                        
                        
                        
                        
                        
                        
                        <div id="tabb2" class="tab_content"> 
                        	<div id="main12">
                    <!-- main grid8 -->
					<div class="grid12">                        
                            <!-- form inside -->
                            <div class="formRow fluid">
                                <!-- form create -->
                                <div class="widget grid6">
                                    <div class="body">
                                    
                                    <div class="formRow fluid">
                                        
            							<div class="grid4">
            								<label><?php echo $this->translate('companytype')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<select name="fac_type" id="selecttype" >
            									<option value="ISO">---- <?php echo $this->translate('selectone')?> ----</option>
            									<option <?php echo ( $getFactory['Fou_Type']=='NF')?$selected:'';?> value="NF">NF</option>
            									<option <?php echo ( $getFactory['Fou_Type']=='ISO')?$selected:'';?>  value="ISO">ISO</option>
            									<option <?php echo ( $getFactory['Fou_Type']=='EUR')?$selected:'';?>  value="EUR">EUR</option>
            								
                                            </select>
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companysiret')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $getFactory['Fou_Siret'];?>" name="fac_siret" id="fac_siret" />
            							</div>							
            							<div class="clear"></div>
            						</div>
            						
            						
            						
                                	
                        
                               
                          </div>
                   </div>
                   
                                <!--The end grid 6 Map2-->
                                
                                <div class="widget grid6">
								<div class="body">		                                
                                	
                                	 <div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companystatus')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<select name="fac_statut" id="selecttype" >
            									<option value="Inactif">---- <?php echo $this->translate('selectstatus')?> ----</option>
            								   
            								  	<option <?php echo ( $getFactory['Fou_Statut']=='Actif')?$selected:'';?> value="Actif">Actif</option>
            								   	<option <?php echo ( $getFactory['Fou_Statut']=='Inactif')?$selected:'';?> value="Inactif">Inactif</option>
                                            </select>
            							</div>
            							<div class="clear"></div>
            						</div>
                                	<div class="formRow fluid">
            
            							<div class="grid4">
            								<label><?php echo $this->translate('codereference')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8"><input type="text" readonly="readonly" value="<?php echo $getFactory['Fou_Refcode'];?>" name="fac_RefCode" id="fac_RefCode" />
            							</div>
            							<div class="clear"></div>
            						</div>
                                  
            						
            						
                                </div>
                             </div>    
                            </div>
                    </div>
                </div>  
                        </div>
                    </div>	
                    <div class="clear"></div>		 
                </div>
                <div class="clear"></div>
                <div class="formRow">
                    <div class="body">
                    <br/>
                         <a class="buttonS bGreyish" href="<?php echo  $this->url(array('Controller'=>'index','action'=>'factory'));?>"><?php echo $this->translate('cancel')?></a>&nbsp;&nbsp;&nbsp;
                        <input class="buttonM bRed" id="back3" value="<?php echo $this->translate('reset')?>" type="reset" />
            			<input class="buttonM bBlue ml10" name="UpdateFactory" value="<?php echo $this->translate('submit')?>" type="submit"/>
                        
                    </div>
                 </div>				
            </div>	
            
            
            	
			
                
            
        </div>
        </form>
        <?php endforeach;?>
        <?php endif;?>
 </div>