<ul class="subNav"  id="nav">
    <li><a href="<?php echo $this->baseUrl();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller;?>/add#" title=""><span class="icos-admin2"></span>Administrator</a></li>
    <li><a href="<?php echo $this->baseUrl();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller;?>/add#" title=""><span class="icos-settings2"></span>Support</a></li>
    <li><a href="<?php echo $this->baseUrl();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller;?>/add#" title=""><span class="icos-users2"></span>Employee</a></li>
</ul>