<?php
    $javascript ='';
    $cssScript = '';
    $pageTitle = $this->translate('addorganisme');
    $cssScript = '<style>.formRow{padding: 5px 16px;}#main12 .widget{margin-top: 15px;}</style>';
	$content = $this->controller.'/'.$this->action.'.phtml';
    require_once TMP_USER_PATH;
?>
<div id="contentdata">
<form name="registerForm" onsubmit="return validateForm()" enctype="multipart/form-data" id="usualValidate" class="main" method="post" action="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/add">
	<div class="wrapper">
	
	<div class="fluid">
                <div class="widget grid12">       
                    <ul class="tabs">
                        <li><a href="#tabb1"><?php echo $this->translate('companytab1')?></a></li>
                        <li><a href="#tabb2"><?php echo $this->translate('companytab2')?></a></li>
                    </ul>
                    
                    <div class="tab_container">
                        <div id="tabb1" class="tab_content">
                            <div id="main12">
                    <!-- main grid8 -->
					<div class="grid12">                        
                            <!-- form inside -->
                            <div class="formRow fluid">
                                <!-- form create -->
                                <div class="widget grid6">
                                    <div class="body">
                                    
                                      <div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companyname')?>:<span class="req">*</span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="" name="Org_name"  id="Org_name" class="required"/>
            							</div>							
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('RaisonSocial')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="" name="Org_social" id="Org_social" />
            							</div>
            						<div class="clear"></div>
            						</div>
            						 <div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companylogo') ?>:</label>
            							</div>
            							<div class="grid8">
            								<input type="file" id="logo" name="fileupload" class="logo"
            									size="100" style="opacity: 0;"/>
            							</div>
            							<div class="clear"></div>
            						</div> 
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companyaddress1')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<div id="addresss"><textarea rows="3" cols="50"  name="Org_address1" id="Org_address1" placeholder="<?php echo $this->translate('selectmap')?>"></textarea></div>
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companycodepostal')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="" name="Org_zipcode" id="Org_zipcode" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companycity')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<div id="states"><input type="text" value="" name="Org_city" id="Org_city" /></div>
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companycountry')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<select name="Org_country" id="country" >
            									<!-- <option value="">-- <?php //echo $this->translate('selectcountry')?> --</option> -->
            									<option value="France">France</option>
            									<option value="France, Metropolitan">France, Metropolitan</option>
            									<option value="French Guiana">French Guiana</option>
            									<option value="French Polynesia">French Polynesia</option>
            									<option value="French Southern Territories">French Southern
            										Territories</option>
            									<option value="Germany">Germany</option>
            									<option value="Italy">Italy</option>
            									<option value="New Zealand">New Zealand</option>
            									<option value="Portugal">Portugal</option>
            									<option value="Sweden">Sweden</option>
            									<option value="Switzerland">Switzerland</option>
            									<option value="Turkey">Turkey</option>
            									<option value="United Kingdom">United Kingdom</option>
            									<option value="United States">United States</option>
            									<option value="United States Minor Outlying Islands">United
            										States Minor Outlying Islands</option>
            								</select>
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companytelephone')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="" name="Org_telephone" id="Org_telephone" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companyfax')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="" name="Org_fax" id="Org_fax" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            						<div class="grid4">
            								<label><?php echo $this->translate('companyemail')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="" name="Org_mail" id="Org_mail" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						 <div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companywebsite')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="" name="Org_website" id="Org_website" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
                          </div>
                   </div>
                
                               
                                <!--The end grid 6-->
                                <div class="widget grid6">
                                 <center><p style="font:bolder;" ><?php echo $this->translate('selectmap')?></p></center>
                                    <div class="body">
                                        <style>
                            		.map {
                            			height: 417px;
                            			width: 100%;
                            		}
                            		.ui-dialog
                            		{
                            			background:#fff;
                            			border:1px solid #ddd;
                            			padding:5px;
                            		}
                            		.ui-dialog-content {height:10px!important;}
                            		</style>
                                    <script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/modernizr.min.js"></script>
                                    <div id="map_canvas" class="map rounded"></div>
                                    <div id="dialog"></div>
                                    
                                    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>  
                                                               		
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/underscore-1.2.2/underscore.min.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/backbone-0.5.3/backbone.min.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/prettify/prettify.min.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/demo.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/jquery.ui.map.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/jquery.ui.map.services.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/jquery.ui.map.extensions.js"></script>
                            		<script type="text/javascript">
                                    <?PHP
                                            $client  = @$_SERVER['HTTP_CLIENT_IP'];
                                            $forward = @$_SERVER['HTTP_X_FORWARDED_FOR'];
                                            $remote  = $_SERVER['REMOTE_ADDR'];
                                            $result  = "France";
                                            if(filter_var($client, FILTER_VALIDATE_IP))
                                            {
                                                $ip = $client;
                                            }
                                            elseif(filter_var($forward, FILTER_VALIDATE_IP))
                                            {
                                                $ip = $forward;
                                            }
                                            else
                                            {
                                                $ip = $remote;
                                            }
                                        
                                            $ip_data = @json_decode(file_get_contents("http://www.geoplugin.net/json.gp?ip=".$ip));
                                        
                                            if($ip_data && $ip_data->geoplugin_countryName != null)
                                            {
                                                $result = $ip_data->geoplugin_countryName;
                                            }
                                            else 
                                            {
                                                $result;
                                            }
                                        $address    = str_replace(" ","+",$result);
                                              /*Query Google Geocoding API */
                                            $ch = curl_init();
                                            curl_setopt($ch, CURLOPT_URL, "http://maps.googleapis.com/maps/api/geocode/xml?address=".$address."&sensor=false");
                                            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                                            $xml = curl_exec($ch);                                            
                                            
                                            //Use SimpleXML library to get the data from the XML string
                                            $xml = new SimpleXMLElement($xml);
                                            $lat = $xml->result[0]->geometry[0]->location[0]->lat;
                                            $lng = $xml->result[0]->geometry[0]->location[0]->lng;
                                            $coords = $lat . "," . $lng;
                                            curl_close($ch); //Close the CURL instance, to keep things tidy                                       
                                        ?>
                                        var mobileDemo = { 'center': '<?php echo $lat;?>,<?php echo $lng;?>', 'zoom': 10 };                                    
                            				demo.add(function() {
                            					$('#map_canvas').gmap({'center': mobileDemo.center, 'zoom': mobileDemo.zoom, 'disableDefaultUI':true, 'callback': function(map) {
                            						var self = this;
                            						self.set('openDialog', function(marker) {
                            							$('#dialog'+marker.__gm_id).dialog({'modal':true, 'title': 'Edit and save point', 'buttons': { 
                            								'No': function() { $(this).dialog('close'); marker.setMap(null); return false; },
                            								'Save': function() { $(this).dialog('close'); return false; }
                            							}});
                            						});
                            						self.set('findLocation', function(location, marker) {
                            							self.search({'location': location}, function(results, status) {
                            								if ( status === 'OK' ) {
                            									$.each(results[0].address_components, function(i,v) {
                            										if ( v.types[0] == "administrative_area_level_1" || v.types[0] == "administrative_area_level_2" ) {
                            											$('#state'+marker.__gm_id).val(v.long_name);
                            										} else if ( v.types[0] == "country") {
                            											$('#country'+marker.__gm_id).val(v.long_name);
                            										}
                            									});
                            									marker.setTitle(results[0].formatted_address);
                            									$('#address'+marker.__gm_id).val(results[0].formatted_address);
                            									self.get('openDialog')(marker);
                            								}
                            							});
                            						});
                            						$(map).click( function(event) {
                            							self.addMarker({'position': event.latLng, 'draggable': true, 'bounds': false}, function(map, marker) {
                            								$('#states').html('<input type="text" id="state'+marker.__gm_id+'" class="txt" name="Org_city" value=""/>');
                            								$('#addresss').html('<textarea rows="3" cols="50" id="address'+marker.__gm_id+'" class="txt" name="Org_address1" ></textarea>');
                            								$('#dialog').append('<form id="dialog'+marker.__gm_id+'" method="get" action="/" style="display:none;">Do you want to save?</form>');
                            								self.get('findLocation')(marker.getPosition(), marker);
                            							}).dragend( function(event) {
                            								self.get('findLocation')(event.latLng, this);
                            							}).click( function() {
                            								self.get('openDialog')(this);
                            							})
                            						});
                            					}});
                            				}).load();                                       	
                                    </script>  
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <div class="formRow fluid"><div class="clear"></div> </div>
                                 
                            </div>
                    </div>
                </div>            
    </div>
                        
                        
                        
                        
                        
                        
                        
                        
                        <div id="tabb2" class="tab_content"> 
                        	<div id="main12">
                    <!-- main grid8 -->
					<div class="grid12">                        
                            <!-- form inside -->
                            <div class="formRow fluid">
                                <!-- form create -->
                                <div class="widget grid6">
                                    <div class="body">
                                    
                                    <div class="formRow fluid">
                                        
            							<div class="grid4">
            								<label><?php echo $this->translate('companytype')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<select name="Org_type" id="selecttype" >
            									<option value="">---- <?php echo $this->translate('selectone')?> ----</option>
            								<?php 
            								  if(count($this->RefCodeTypeFromController)!=0){
            								 foreach ($this->RefCodeTypeFromController as $getReftypeRecord){
            								?>
            								 <option value="<?php echo $getReftypeRecord["ref_code_lib"]; ?>"><?php echo $getReftypeRecord["ref_Description"]; ?></option>	
            								<?php 
            									}
            								 }
            								?>
            								
                                            </select>
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companysiret')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="" name="Org_siret" id="Org_siret" />
            							</div>							
            							<div class="clear"></div>
            						</div>
            						<div class="formRow fluid">
            							
                                        <div class="grid4"><label><?php echo $this->translate('companystatus')?>:<span class="req"></span></label></div>
            							<div class="grid8">
            								<select name="Org_statut" id="selecttype" >
            									<option value="Inactif">---- <?php echo $this->translate('selectone')?> ----</option>
            								   
            								  <?php 
            								  if(count($this->RefStatusFromController)!=0){
            								 foreach ($this->RefStatusFromController as $getRefStatusRecord){
            								?>
            								 <option value="<?php echo $getRefStatusRecord["ref_code_lib"]; ?>"><?php echo $getRefStatusRecord["ref_Description"]; ?></option>	
            								<?php 
            									}
            								 }
            								?>
                                            </select>
            							</div>
            							<div class="clear"></div>
            						</div>
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companyTVA')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="" name="Org_vat" id="Org_vat" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
                                	
                        
                               
                          </div>
                   </div>
                
                               
                               
                               
                                <!--The end grid 6 Map2-->
                                
                                <div class="widget grid6">
								<div class="body">		                                
                                	
                                	 <div class="formRow fluid">
            							<div class="grid4">
            								<label><?php //echo $this->translate('companydecription')?>Description:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<textarea  style="height: 64px;" rows="2" cols="50"   name="Org_decription" id="Org_decription" ></textarea>
            							</div>
            							<div class="clear"></div>
            						</div>
                                	<div class="formRow fluid">
            
            							<div class="grid4">
            								<label><?php echo $this->translate('codereference')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<select name="Org_RefCode" id="selectreference" >
            									<option value="">---- <?php echo $this->translate('selectone')?> ----</option>
            								<?php 
            								if(count($this->RefCodeTypeFromController)!=0){
            	  							foreach ($this->RefCodesFromController as $GetRefCode){
            	  	 							 
            	  	 							?>
            	  	 							<option value="<?php echo $GetRefCode['ref_code_lib'];?>"><?php echo $GetRefCode['ref_code_lib'];?></option>
            	  	 							<?php 
            	  								}
            	  							}
            								?>
            								
            							 </select>
            							</div>
            							<div class="clear"></div>
            						</div>
                                   
						
            						
            						 <div class="formRow fluid noBorderB">
        			                        <div class="grid4"><label><?php echo $this->translate('companylevel')?>:<span class="req"></span></label></div>
        	                        <div class="grid8">
        		                        <select name="Org_Level" id="changeOnSelect" >
        									<option value="Non" id="selectlevel">---- <?php echo $this->translate('selectone')?> ----</option>
        									<?php 
        										if(count($this->RefLevelFromController)!=0){
        			  							foreach ($this->RefLevelFromController as $GetRefLevel){
        			  	 							 
        			  	 							?>
        			  	 							<option value="<?php echo $GetRefLevel['ref_code_lib'];?>"><?php echo $GetRefLevel['ref_code_lib'];?></option>
        			  	 							<?php 
        			  								}
        			  							}
        								?>
        								 </select>
        								 <script> 
        								$('#changeOnSelect').change(function(){
                                        $('.showOnSelect').hide();
                                        $('#' + $(this).val()).show();
                                        });
        							</script>
        	                        </div>
        	                        <div class="clear"></div>
                     			</div>
                     			 <div  id="Oui" class="showOnSelect" style="display: none;">  
        						  	<h6 style="display: block;font-size: 12px;font-weight: bold;padding: 8px 14px 7px;text-align: center;color: #2E6B9B;">Hierarchie Organisme</h6>
        
								    <div class="formRow fluid">
        			                        <div class="grid4"><label>CodeFunction:<span class="req"></span></label></div>
        			                        <div class="grid8">
        			                               <select name="horg_codefuntion" id="horg_codefuntion" >
        									<option value="">---- <?php echo $this->translate('selectone')?> ----</option>
        								<?php 
        								if(count($this->RefCodeFunctionFromController)!=0){
        	  							foreach ($this->RefCodeFunctionFromController as $GetRefCodeFunction){
        	  	 							 
        	  	 							?>
        	  	 							<option value="<?php echo $GetRefCodeFunction['ref_code_lib'];?>"><?php echo $GetRefCodeFunction['ref_Description'];?></option>
        	  	 							<?php 
        	  								}
        	  							}
        								?>
        								
        							 </select>  
        			                        
        			                        </div>
        			                        <div class="clear"></div>
        			                   </div>
        			                  <div class="formRow fluid">     
        			                        <div class="grid4"><label>Secondaire:<span class="req"></span></label></div>
        			                        <div class="grid8"><input type="text" value="" name="horg_secondaire" id="horg_secondaire" /></div>
        			                        <div class="clear"></div>
        		             			</div>
        								
        			                    <div class="formRow fluid">    
        			                        <div class="grid4"><label>Description:<span class="req"></span></label></div>
        			                        <div class="grid8"><input type="text" value="" name="horg_description" id="horg_description" /></div>
        			                        <div class="clear"></div>
        		             			</div>
        		             			<div class="formRow fluid">
        			                        <div class="grid4"><label>statut:<span class="req"></span></label></div>
        			                        <div class="grid8">
        			                        	<select name="Horg_level" id="Horg_level" >
        											<option value="">---- <?php echo $this->translate('selectstatus')?> ----</option>
        											<option value="<?php echo $this->translate('yes')?>"><?php echo $this->translate('yes')?></option>
        											<option value="<?php echo $this->translate('no')?>"><?php echo $this->translate('no')?></option>
        										</select>
        			                        </div>
        			                        
        			                        <div class="clear"></div>
        		             			</div>
                                        
                       			</div>
            						
            						
                                </div>
                                <div class="clear"></div>
                                
                             </div>    
                            </div>
                    </div>
                </div>  
                        </div>
                    </div>	
                    <div class="clear"></div>		 
                </div>
                <div class="clear"></div>
                <div class="formRow">
                    <div class="body">
                    <br/>
                         <a class="buttonS bGreyish" href="<?php echo  $this->url(array('Controller'=>'organisme','action'=>'index'));?>"><?php echo $this->translate('cancel')?></a>&nbsp;&nbsp;&nbsp;
                        <input class="buttonM bRed" id="back3" value="<?php echo $this->translate('reset')?>" type="reset" />
            			<input class="buttonM bBlue ml10" name="SaveOrg" value="<?php echo $this->translate('submit')?>" type="submit"/>
                        
                    </div>
                 </div>				
            </div>	
            
            
            	
			
                
            
        </div>
        </form>
 </div>