  <?php
			$javascript = '';
			$cssScript = '';
			$pageTitle = $this->translate('edit');
			$content = $this->controller . '/' . $this->action . '.phtml';
            $cssScript = '<style>.formRow{padding: 5px 16px;}#main12 .widget{margin-top: 15px;}</style>';
            $breadLinks = '<ul><li><a title="" href="'.$this->url(array('Controller' => '', 'action' => 'add')).'"><i class="icos-add"></i><span>'.$this->translate('create').'</span><strong></strong></a></li></ul>';
			require_once TMP_USER_PATH;
			?>
<div id="contentdata">
 <?php  foreach ($this->EditOrganisme as $Values):?>
<form name="registerForm" onsubmit="return validateForm()" enctype="multipart/form-data" id="usualValidate" class="main" method="post" action="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/edit?getidform=<?php echo $Values['Com_Id'];?>">
	<div class="wrapper">
	
	<div class="fluid">
                <div class="widget grid12">       
                    <ul class="tabs">
                        <li><a href="#tabb1"><?php echo $this->translate('companytab1')?></a></li>
                        <li><a href="#tabb2"><?php echo $this->translate('companytab2')?></a></li>
                    </ul>
                    
                    <div class="tab_container">
                        <div id="tabb1" class="tab_content">
                            <div id="main12">
                    <!-- main grid8 -->
					<div class="grid12">                        
                            <!-- form inside -->
                            <div class="formRow fluid">
                                <!-- form create -->
                                <div class="widget grid6">
                                    <div class="body">
                                    
                    				    <?php  $selected='selected'; ?>
                                        <input type="hidden" name="hiddenID" value="<?php echo $Values['Com_Id'];?>" />
                                      <div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companyname')?>:<span class="req">*</span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $Values['Com_Name'];?>" name="Org_name"  id="Org_name" class="required"/>
            							</div>							
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('RaisonSocial')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $Values['Com_RaisonSocial'];?>" name="Org_social" id="Org_social" />
            							</div>
            						<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companylogo') ?>:</label>
            							</div>
            							<div class="grid8">
            								<input type="file" id="logo" name="fileupload" class="logo"
            									size="18.5" style="opacity: 0;"/>
            							</div>
            							<div class="clear"></div>
            						</div> 
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companyaddress1')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<div id="addresss"><textarea rows="3" cols="50"  name="Org_address1" id="Org_address1" ><?php echo $Values['Com_Address1'];?></textarea></div>
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companycodepostal')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $Values['Com_ZipCode'];?>" name="Org_zipcode" id="Org_zipcode" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companycity')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<div id="states"><input type="text" value="<?php echo $Values['Com_City'];?>" name="Org_city" id="Org_city" /></div>
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companycountry')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<select name="Org_country" id="country" >
            									<option value="France">France</option>
                									<option
                										<?php echo ($Values['Com_Country']=='France')?$selected:'' ;?>
                										value="France">France</option>
                									<option
                										<?php echo ($Values['Com_Country']=='France, Metropolitan')?$selected:'' ;?>
                										value="France, Metropolitan">France, Metropolitan</option>
                									<option
                										<?php echo ($Values['Com_Country']=='French Guiana')?$selected:'' ;?>
                										value="French Guiana">French Guiana</option>
                									<option
                										<?php echo ($Values['Com_Country']=='French Polynesia')?$selected:'' ;?>
                										value="French Polynesia">French Polynesia</option>
                									<option
                										<?php echo ($Values['Com_Country']=='French Southern Territories')?$selected:'' ;?>
                										value="French Southern Territories">French SouthernTerritories</option>
                									<option
                										<?php echo ($Values['Com_Country']=='Germany')?$selected:'' ;?>
                										value="Germany">Germany</option>
                									<option
                										<?php echo ($Values['Com_Country']=='Italy')?$selected:'' ;?>
                										value="Italy">Italy</option>
                									<option
                										<?php echo ($Values['Com_Country']=='New Zealand')?$selected:'' ;?>
                										value="New Zealand">New Zealand</option>
                									<option
                										<?php echo ($Values['Com_Country']=='Portugal')?$selected:'' ;?>
                										value="Portugal">Portugal</option>
                									<option
                										<?php echo ($Values['Com_Country']=='Sweden')?$selected:'' ;?>
                										value="Sweden">Sweden</option>
                									<option
                										<?php echo ($Values['Com_Country']=='Switzerland')?$selected:'' ;?>
                										value="Switzerland">Switzerland</option>
                									<option
                										<?php echo ($Values['Com_Country']=='Turkey')?$selected:'' ;?>
                										value="Turkey">Turkey</option>
                									<option
                										<?php echo ($Values['Com_Country']=='United Kingdom')?$selected:'' ;?>
                										value="United Kingdom">United Kingdom</option>
                									<option
                										<?php echo ($Values['Com_Country']=='United States')?$selected:'' ;?>
                										value="United States">United States</option>
                									<option
                										<?php echo ($Values['Com_Country']=='United States Minor Outlying Islands')?$selected:'' ;?>
                										value="United States Minor Outlying Islands">United States
                										Minor Outlying Islands</option>
            								</select>
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companytelephone')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $Values['Com_Telephone'];?>" name="Org_telephone" id="Org_telephone" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companyfax')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $Values['Com_Fax'];?>" name="Org_fax" id="Org_fax" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            						<div class="grid4">
            								<label><?php echo $this->translate('companyemail')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $Values['Com_Mail'];?>" name="Org_mail" id="Org_mail" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						 <div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companywebsite')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $Values['Com_Website'];?>" name="Org_website" id="Org_website" />
            							</div>
            							<div class="clear"></div>
            						</div>
            						
                          </div>
                   </div>
                
                               
                                <!--The end grid 6-->
                                <div class="widget grid6">
                                 <center><p style="font:bolder;" ><?php echo $this->translate('selectmap')?></p></center>
                                    <div class="body">
                                        <style>
                            		.map {
                            			height: 435px;
                            			width: 100%;
                            		}
                            		.ui-dialog
                            		{
                            			background:#fff;
                            			border:1px solid #ddd;
                            			padding:5px;
                            		}
                            		.ui-dialog-content {height:10px!important;}
                            		</style>
                                    <script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/modernizr.min.js"></script>
                                    <div id="map_canvas" class="map rounded"></div>
                                    <div id="dialog"></div>
                                    
                                    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>  
                                                               		
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/underscore-1.2.2/underscore.min.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/backbone-0.5.3/backbone.min.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/prettify/prettify.min.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/demo.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/jquery.ui.map.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/jquery.ui.map.services.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/jquery.ui.map.extensions.js"></script>
                            		<script type="text/javascript">
                                    <?PHP
                                    /* for Convert accented characters to their plain ascii equivalents By Socheat Ngann */
                                    $normalizeChars = array(
                                        'Š'=>'S', 'š'=>'s', 'Ð'=>'Dj','Ž'=>'Z', 'ž'=>'z', 'À'=>'A', 'Á'=>'A', 'Â'=>'A', 'Ã'=>'A', 'Ä'=>'A',
                                        'Å'=>'A', 'Æ'=>'A', 'Ç'=>'C', 'È'=>'E', 'É'=>'E', 'Ê'=>'E', 'Ë'=>'E', 'Ì'=>'I', 'Í'=>'I', 'Î'=>'I',
                                        'Ï'=>'I', 'Ñ'=>'N', 'Ò'=>'O', 'Ó'=>'O', 'Ô'=>'O', 'Õ'=>'O', 'Ö'=>'O', 'Ø'=>'O', 'Ù'=>'U', 'Ú'=>'U',
                                        'Û'=>'U', 'Ü'=>'U', 'Ý'=>'Y', 'Þ'=>'B', 'ß'=>'Ss','à'=>'a', 'á'=>'a', 'â'=>'a', 'ã'=>'a', 'ä'=>'a',
                                        'å'=>'a', 'æ'=>'a', 'ç'=>'c', 'è'=>'e', 'é'=>'e', 'ê'=>'e', 'ë'=>'e', 'ì'=>'i', 'í'=>'i', 'î'=>'i',
                                        'ï'=>'i', 'ð'=>'o', 'ñ'=>'n', 'ò'=>'o', 'ó'=>'o', 'ô'=>'o', 'õ'=>'o', 'ö'=>'o', 'ø'=>'o', 'ù'=>'u',
                                        'ú'=>'u', 'û'=>'u', 'ý'=>'y', 'ý'=>'y', 'þ'=>'b', 'ÿ'=>'y', 'ƒ'=>'f'
                                    );
                                    if(!empty($Values['Com_Address1']))
                                    {
                                            $address    = str_replace(" ","+",$Values['Com_Address1']) . ",+" . str_replace(" ","+",$Values['Com_City']) . ",+" . str_replace(" ","+",$Values['Com_Country']);
                                            $address        = strtr($address, $normalizeChars);
                                              /*Query Google Geocoding API */
                                            $ch = curl_init();
                                            curl_setopt($ch, CURLOPT_URL, "http://maps.googleapis.com/maps/api/geocode/xml?address=".$address."&sensor=false");
                                            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                                            $xml = curl_exec($ch);                                            
                                            
                                            //Use SimpleXML library to get the data from the XML string
                                            $xml = new SimpleXMLElement($xml);
                                            $lat = $xml->result[0]->geometry[0]->location[0]->lat;
                                            $lng = $xml->result[0]->geometry[0]->location[0]->lng;
                                            $coords = $lat . "," . $lng;
                                            curl_close($ch); //Close the CURL instance, to keep things tidy 
                                    
                                    
                                    }
                                    else
                                    {
                                            $client  = @$_SERVER['HTTP_CLIENT_IP'];
                                            $forward = @$_SERVER['HTTP_X_FORWARDED_FOR'];
                                            $remote  = $_SERVER['REMOTE_ADDR'];
                                            $result  = "France";
                                            if(filter_var($client, FILTER_VALIDATE_IP))
                                            {
                                                $ip = $client;
                                            }
                                            elseif(filter_var($forward, FILTER_VALIDATE_IP))
                                            {
                                                $ip = $forward;
                                            }
                                            else
                                            {
                                                $ip = $remote;
                                            }
                                        
                                            $ip_data = @json_decode(file_get_contents("http://www.geoplugin.net/json.gp?ip=".$ip));
                                        
                                            if($ip_data && $ip_data->geoplugin_countryName != null)
                                            {
                                                $result = $ip_data->geoplugin_countryName;
                                            }
                                            else 
                                            {
                                                $result;
                                            }
                                        $address    = str_replace(" ","+",$result);
                                        $address    = strtr($address, $normalizeChars);
                                              /*Query Google Geocoding API */
                                            $ch = curl_init();
                                            curl_setopt($ch, CURLOPT_URL, "http://maps.googleapis.com/maps/api/geocode/xml?address=".$address."&sensor=false");
                                            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                                            $xml = curl_exec($ch);                                            
                                            
                                            //Use SimpleXML library to get the data from the XML string
                                            $xml = new SimpleXMLElement($xml);
                                            $lat = $xml->result[0]->geometry[0]->location[0]->lat;
                                            $lng = $xml->result[0]->geometry[0]->location[0]->lng;
                                            $coords = $lat . "," . $lng;
                                            curl_close($ch); //Close the CURL instance, to keep things tidy
                                    }                                            
                                        ?> 
                                            var mobileDemo = { 'center': '<?php echo $lat;?>,<?php echo $lng;?>', 'zoom': 10 };                                   
                            				demo.add(function() {
                            					$('#map_canvas').gmap({'center': mobileDemo.center, 'zoom': mobileDemo.zoom, 'disableDefaultUI':true, 'callback': function(map) {
                            						var self = this;
                            						self.set('openDialog', function(marker) {
                            							$('#dialog'+marker.__gm_id).dialog({'modal':true, 'title': 'Edit and save point', 'buttons': { 
                            								'No': function() { $(this).dialog('close'); marker.setMap(null); return false; },
                            								'Save': function() { $(this).dialog('close'); return false; }
                            							}});
                            						});
                            						self.set('findLocation', function(location, marker) {
                            							self.search({'location': location}, function(results, status) {
                            								if ( status === 'OK' ) {
                            									$.each(results[0].address_components, function(i,v) {
                            										if ( v.types[0] == "administrative_area_level_1" || v.types[0] == "administrative_area_level_2" ) {
                            											$('#state'+marker.__gm_id).val(v.long_name);
                            										} else if ( v.types[0] == "country") {
                            											$('#country'+marker.__gm_id).val(v.long_name);
                            										}
                            									});
                            									marker.setTitle(results[0].formatted_address);
                            									$('#address'+marker.__gm_id).val(results[0].formatted_address);
                            									self.get('openDialog')(marker);
                            								}
                            							});
                            						});
                            						$(map).click( function(event) {
                            							self.addMarker({'position': event.latLng, 'draggable': true, 'bounds': false}, function(map, marker) {
                            								$('#states').html('<input type="text" id="state'+marker.__gm_id+'" class="txt" name="Org_city" value=""/>');
                            								$('#addresss').html('<textarea rows="3" cols="50" id="address'+marker.__gm_id+'" class="txt" name="Org_address1" ></textarea>');
                            								$('#dialog').append('<form id="dialog'+marker.__gm_id+'" method="get" action="/" style="display:none;">Do you want to save?</form>');
                            								self.get('findLocation')(marker.getPosition(), marker);
                            							}).dragend( function(event) {
                            								self.get('findLocation')(event.latLng, this);
                            							}).click( function() {
                            								self.get('openDialog')(this);
                            							})
                            						});
                            					}});
                            				}).load();                           	
                                    </script> 
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <div class="formRow fluid"><div class="clear"></div> </div>
                                 
                            </div>
                    </div>
                </div>            
    </div>
                        
                        
                        
                        
                        
                        
                        
                        
                        <div id="tabb2" class="tab_content"> 
                        	<div id="main12">
                    <!-- main grid8 -->
					<div class="grid12">                        
                            <!-- form inside -->
                            <div class="formRow fluid">
                                <!-- form create -->
                                <div class="widget grid6">
                                    <div class="body">
                                    
                                    <div class="formRow fluid">
                                        
            							<div class="grid4">
            								<label><?php echo $this->translate('companytype')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<select name="Org_type" id="selecttype" >
            									<option value="">---- <?php echo $this->translate('selectone')?> ----</option>
            								<?php 
            								  if(count($this->RefCodeTypeFromController)!=0){
            								 foreach ($this->RefCodeTypeFromController as $getReftypeRecord){
            								?>
            								 <option <?php echo ($Values['Com_Type']==$getReftypeRecord['ref_code_lib'])?$selected:'';?>  value="<?php echo $getReftypeRecord["ref_code_lib"]; ?>"><?php echo $getReftypeRecord["ref_Description"]; ?></option>	
            								<?php 
            									}
            								 }
            								?>
            								
                                            </select>
            							</div>
            							<div class="clear"></div>
            						</div>
            						
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companysiret')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $Values['Com_Siret'];?>" name="Org_siret" id="Org_siret" />
            							</div>							
            							<div class="clear"></div>
            						</div>
            						<div class="formRow fluid">
            							
                                        <div class="grid4"><label><?php echo $this->translate('companystatus')?>:<span class="req"></span></label></div>
            							<div class="grid8">
            								<select name="Org_statut" id="selecttype" >
            									<option value="Inactif">---- <?php echo $this->translate('selectstatus')?> ----</option>
            								   
            								  <?php 
            								  if(count($this->RefStatusFromController)!=0){
            								 foreach ($this->RefStatusFromController as $getRefStatusRecord){
            								?>
            								 <option <?php echo ($Values['Com_Status']==$getRefStatusRecord['ref_code_lib'])?$selected:'';?> value="<?php echo $getRefStatusRecord["ref_code_lib"]; ?>"><?php echo $getRefStatusRecord["ref_Description"]; ?></option>	
            								<?php 
            									}
            								 }
            								?>
                                            </select>
            							</div>
            							<div class="clear"></div>
            						</div>
            						<div class="formRow fluid">
            							<div class="grid4">
            								<label><?php echo $this->translate('companyTVA')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<input type="text" value="<?php echo $Values['Com_VAT'];?>" name="Org_vat" id="Org_vat" />
            							</div>
            							<div class="clear"></div>
            						</div>
                        
                               
                          </div>
                   </div>
                
                               
                               
                               
                                <!--The end grid 6 Map2-->
                                
                                <div class="widget grid6">
								<div class="body">		                                
                                	
                                	 <div class="formRow fluid">
            							<div class="grid4">
            								<label><?php //echo $this->translate('companydecription')?>Description:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<textarea  style="height: 64px;" rows="5" cols="50" name="Org_decription" id="Org_decription" ><?php echo $Values['Com_description'];?></textarea>
            							</div>
            							<div class="clear"></div>
            						</div>
                                	
                                	<div class="formRow fluid">
            
            							<div class="grid4">
            								<label><?php echo $this->translate('codereference')?>:<span class="req"></span></label>
            							</div>
            							<div class="grid8">
            								<select name="Org_RefCode" id="selectreference" >
            									<option value="">---- <?php echo $this->translate('selectone')?> ----</option>
            								<?php 
            								if(count($this->RefCodeTypeFromController)!=0){
            	  							foreach ($this->RefCodesFromController as $GetRefCode){
            	  	 							 
            	  	 							?>
            	  	 							<option <?php echo ($Values['Com_Refcode']==$GetRefCode['ref_code_lib'])?$selected:'';?> value="<?php echo $GetRefCode['ref_code_lib'];?>"><?php echo $GetRefCode['ref_Description'];?></option>
            	  	 							<?php 
            	  								}
            	  							}
            								?>
            								
            							 </select>
            							</div>
            							<div class="clear"></div>
            						</div>
                                   
						
            						 
            						 <div class="formRow fluid">
        			                        <div class="grid4"><label><?php echo $this->translate('companylevel')?>:<span class="req"></span></label></div>
        	                        <div class="grid8">
        		                        <select name="Org_Level" id="changeOnSelect" >
        									<option value="Non" id="selectlevel">---- <?php echo $this->translate('selectone')?> ----</option>
        									<?php 
        										if(count($this->RefLevelFromController)!=0){
        			  							foreach ($this->RefLevelFromController as $GetRefLevel){
        			  	 							 
        			  	 							?>
        			  	 							<option <?php echo ($Values['Com_level']==$GetRefLevel['ref_code_lib'])?$selected:'';?> value="<?php echo $GetRefLevel['ref_code_lib'];?>"><?php echo $GetRefLevel['ref_code_lib'];?></option>
        			  	 							<?php 
        			  								}
        			  							}
        								?>
        								 </select>
        								 <script> 
        								$('#changeOnSelect').change(function(){
                                        $('.showOnSelect').hide();
                                        $('#' + $(this).val()).show();
                                        });
        							</script>
        	                        </div>
        	                        <div class="clear"></div>
                     			</div>
                     			 <div  id="Oui" class="showOnSelect" style="<?php echo ($Values['Com_level']=="Oui")?"display: block;":"display: none;" ?> ">  
        						  	<h6 style="display: block;font-size: 12px;font-weight: bold;padding: 8px 14px 7px;text-align: center;color: #2E6B9B;">Hierarchie Organisme</h6>
        
								    <div class="formRow fluid">
        			                        <div class="grid4"><label>CodeFunction:<span class="req"></span></label></div>
        			                        <div class="grid8">
        			                               <select name="horg_codefuntion" id="horg_codefuntion" >
        									<option value="">---- <?php echo $this->translate('selectone')?> ----</option>
        								<?php 
        								if(count($this->RefCodeFunctionFromController)!=0){
        	  							foreach ($this->RefCodeFunctionFromController as $GetRefCodeFunction){
        	  	 							 
        	  	 							?>
        	  	 							<option <?php echo ($Values['horg_Codefunction']== $GetRefCodeFunction['ref_code_lib'])?$selected:'';?> value="<?php echo $GetRefCodeFunction['ref_code_lib'];?>"><?php echo $GetRefCodeFunction['ref_Description'];?></option>
        	  	 							<?php 
        	  								}
        	  							}
        								?>
        								
        							 </select>  
        			                        
        			                        </div>
        			                        <div class="clear"></div>
        			                   </div>
        			                  <div class="formRow fluid">     
        			                        <div class="grid4"><label>Secondaire:<span class="req"></span></label></div>
        			                        <div class="grid8"><input type="text" value="<?php echo $Values['horg_Secondaire'];?>" name="horg_secondaire" id="horg_secondaire" /></div>
        			                        <div class="clear"></div>
        		             			</div>
        								
        			                    <div class="formRow fluid">    
        			                        <div class="grid4"><label>Description:<span class="req"></span></label></div>
        			                        <div class="grid8"><input type="text" value="<?php echo $Values['horg_description'];?>" name="horg_description" id="horg_description" /></div>
        			                        <div class="clear"></div>
        		             			</div>
        		             			<div class="formRow fluid">
        			                        <div class="grid4"><label>statut:<span class="req"></span></label></div>
        			                        <div class="grid8">
        			                        	<select name="Horg_level" id="Horg_level" >
        											<option value="">---- <?php echo $this->translate('selectstatus')?> ----</option>
        											<option <?php echo ($Values['horg_status']=="Oui")?$selected:'';?> value="<?php echo $this->translate('yes')?>"><?php echo $this->translate('yes')?></option>
        											<option <?php echo ($Values['horg_status']=="Non")?$selected:'';?> value="<?php echo $this->translate('no')?>"><?php echo $this->translate('no')?></option>
        										</select>
        			                        </div>
        			                        
        			                        <div class="clear"></div>
        		             			</div>
                                        
                       			</div>
            						
            						
                                </div>
                                <div class="clear"></div>
                                
                             </div>    
                            </div>
                    </div>
                </div>  
                        </div>
                    </div>	
                    <div class="clear"></div>		 
                </div>
                <div class="clear"></div>
                  <script type="text/javascript">
                                    function backindex(){
                                         window.location.href="<?php echo $this->url(array('controller'=>'Organisme','action'=>'index'));?>";
                                       
                                    }
                                </script>
                <div class="body">
                	<br />              
                                        <button type="button" class="buttonS bRed" onclick="backindex();"><?php echo $this->translate('cancel')?></button>
                                        <input type="submit" value="<?php echo $this->translate('update')?>" name="OrgUpdate" class="buttonS bBlue"/>
                    
                </div>
                 				
            </div>	
                   
        </div>
        </form>
         <?php endforeach;?>    
 </div>