<?php
$javascript = '';
$cssScript = '';
$pageTitle = $this->translate('equipementref');
$cssScript = '<style>.formRow{padding: 5px 16px;}#main8 .widget{margin-top: 15px;}</style>';
$content = $this->controller . '/' . $this->action . '.phtml';
$breadLinks = '<ul><li><a title="" href="'.$this->baseUrl ().'/'.$this->translate('lang').'/'.$this->controller.'/equipementadd"><i class="icos-add"></i><span>'.$this->translate('create').'</span><strong></strong></a></li></ul>';
require_once TMP_USER_PATH;
?>
<style type="text/css">
.cuser {float:right;margin:20px 0 -20px 0}
.adduser {font-size:20px;float:right;}
.addusertxt {float:right;padding: 0 0 0 5px;
 font-size: 16px;
    font-weight: bold;
    line-height: 23px;
    margin-left: 0;
    padding: 0 5px;
    padding-right: 15px;
    text-decoration: none;
    text-shadow: 1px 1px #EFEFEF;
}
</style>
<script type="text/javascript">
	$(document).ready(function(){
	    $("#research").hide();
        $("#basic_search").show();
	$('#advancedsearch').click(function(){
    $("#basic_search").hide();
	$("#research").slideToggle();
	$("#research").show();
	$("#basicsearch").click(function(){
		 $("#research").hide();
         $("#basic_search").show();
		});
	});
});
</script>
<div id="contentdata">
	<div class="wrapper">
			<div class="tab_container">
			 <div id="search" class="tab_content">
		      	<div class="widget fluid tableTabs">
		      	<form  method="get" action="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/equipementindex">
    				 <!-- basic search-->
    				  <div id="basic_search">
                           <div class="formRow">                        
        						<div class="grid1">
        							<label><?php echo $this->translate('companyname')?>&nbsp;&nbsp;<b>:</b>
        							</label>
        						</div>
        						<div class="grid3">
        							<input type="text" name="txtnamebasicsearch" />
        						</div>
        						<div class="grid8">
        							<input type="submit" value="<?php echo $this->translate('search')?>" class="buttonM bDefault" name="btnbasicsearch"/>
        							&nbsp;&nbsp;
                                    <input type="reset" value="<?php echo $this->translate('reset')?>" class="buttonM bDefault"/>
        							&nbsp;&nbsp;
                                   <!--<a href="#"><span id="advancedsearch"><?php //echo $this->translate('advancesearch')?></span></a> -->
        						</div>
        						<div class="clear"></div>
                            </div>
                        </div>
                       <!-- end basic search-->  	
               </form> 
            </div>
            <form method="post"
			action="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/equipementdelete"
			id="SiteForm" name="SiteForm">
            <div class="widget check">
                    <div class="whead">
						<span class="titleIcon"> <input type="checkbox" id="titleCheck"
							name="titleCheck" />
						</span>
						<h6><?php echo $this->translate('viewsite')?></h6>
						<div class="clear"></div>
					</div>
                    <div id="dyn2" class="shownpars">                    
                    <table cellpadding="0" cellspacing="0" width="100%"
						class="dTable tDefault checkAll tMedia" id="checkAll">
						<thead>
							<tr>
								<td><img src="<?php echo $this->baseUrl();?>/images/elements/other/tableArrows.png" alt="" /></td>
								<!--
<td width="100"><?php //echo $this->translate('edit')?></td>
-->
								<td class="sortCol" width="150"><div>
										N<sup>o</sup>&nbsp;&nbsp;<?php //echo $this->translate('reference')?><span></span>
									</div></td>
								<td class="sortCol" width="150"><div>
										Equipment <?php //echo $this->translate('companyname')?><span></span>
									</div></td>
								<td class="sortCol">Type Equipment<div><span></span>
									</div></td>
								<td class="sortCol">Factory<div><?php //echo $this->translate('reference')?>
										<span></span>
									</div></td>
								<td class="sortCol"><div>
									  SKU<span></span>
									</div></td>
								<td class="sortCol"><div>
										<?php echo $this->translate('warranty')?><span></span>
									</div></td>									
									<!--
<td class="sortCol"><div>
										<?php //echo $this->translate('siteacontroler')?><span></span>
									</div></td>
-->
								<td width="100">Actions</td>
							</tr>
						</thead> 
						<!-- Multiple delete action -->
                        <tfoot>
						      <tr>
								<td colspan="8">
									<div class="itemActions">										
										<select id="actionSelect" name="multiAction">
											<option value="">---- <?php echo $this->translate('selectone')?> ----</option>
											<option value="delete"><?php echo $this->translate('delete')?></option>
										</select>
									</div>
									<input onclick="return confirm('<?php echo $this->translate('areyousure') ?>')" style="margin-top: 6px; margin-left: 5px; height: 28px;" class="tablectrl_medium bDefault" type="submit"  value="<?php echo $this->translate('apply')?>" name="btnDeleteMultiequip" />

	   				
								</td>
								
							</tr>
						</tr>
						
						</tfoot>
                       <!-- Multiple delete action -->
						<tbody>
                    <?php 
								if(count($this->getallrecordEquipement)!=0){
									foreach ($this->getallrecordEquipement as $alldata){
						?> 
	   				    <tr class="row<?php echo $alldata['equip_id']?>">
	   					<td><input type="checkbox" name="checkRow[]" value="<?php echo $alldata['equip_id'];?>" /></td>
		                </td>
	   					<td>000<?php echo $alldata['equip_id'];?></td>	
	   					<td><a href="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/equipementview?actions=overview&id=<?php echo $alldata['equip_id']; ?>"><?php echo $alldata['equip_name'];?></a></td>
	   					<td><a href="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/equipementview?actions=overview&id=<?php echo $alldata['equip_id']; ?>"><?php echo $alldata['type_name'];?></a></td>
	   					<td><?php echo $alldata['Fou_Name'];?></td>
	   					<td><?php echo  $alldata['equip_SKU'];?></td>
	   					<td><?php echo $alldata['equip_warranty'];?></td>
	   					<td class="tableActs noBorderB" align="center">
                            <a href="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/equipementedit?actions=edit&id=<?php echo $alldata['equip_id'];?>" class="tablectrl_small bBlue tipS" original-title="<?php echo $this->translate('edit')?>"><span class="iconb" data-icon="&#xe1db;"></span></a>
                            <a href="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/equipementdelete?actions=delete&id=<?php echo $alldata['equip_id'];?>" class="tablectrl_small bRed tipS" original-title="<?php echo $this->translate('remove')?>" onclick="return confirm('<?php echo $this->translate('areyousure') ?>')"><span class="iconb" data-icon="&#xe136;"></span></a>
                            
                        </td>
	   				</tr>
	   				<?php 
	   					}
	   				}
 					?>
						</tbody>
					</table>
                    </div>
            </div>
            </form>
    	</div>
</div>
	<div class="clear"></div>
 

	
</div>
</div>