<?php
    $javascript ='';
    $cssScript = '<style>.widget .body{background:#fff;padding:0;}.widget{border:1px solid #ddd;}
    td:first-child { background:#eee}td:first-child + td { font-weight:bold;background:#fff;}background:#eee}td:first-child + td { font-weight:bold;background:#fff;}td:first-child + td + td { font-weight:bold;background:#eee;}td:first-child + td + td + td{ font-weight:bold;background:#fff;}#map_canvas {height: 270px;width: 100%;}</style>';
    $pageTitle =$this->translate('overview');
    $breadLinks = '<ul><li><a title="" href="'.$this->baseUrl ().'/'.$this->translate('lang').'/'.$this->controller.'/addfactory"><i class="icos-add"></i><span>'.$this->translate('create').'</span><strong></strong></a></li></ul>';
	$content = $this->controller.'/'.$this->action.'.phtml';
    require_once TMP_USER_PATH;
?>
<?php 
                                    if (count($this->factoryOverview)!=0):
                                    foreach ($this->factoryOverview as $rows):
                                    
                                  ?>
<div id="contentdata"> 
    <div class="wrapper">
        <div class="fluid">
            <div class="widget grid12">       
                <ul class="tabs">
                    <a class="buttonH bRed right" href="<?php echo  $this->url(array('Controller'=>'factory','action'=>'index'));?>"><?php echo $this->translate('back')?></a>
				    <a title="" class="buttonH bBlue right" href="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/editfactory?actions=edit&id=<?php echo $rows['Fou_Id'];?>"><?php echo $this->translate('edit')?></a>
                    <li class="activeTab"><a href="#tabb1"><?php echo $this->translate('overview')?></a></li>                                    
                </ul>                
                <div class="tab_container">
                    <div class="tab_content" id="tabb1" style="display: block;">
                    <div class="widget justTable grid4">
                        <div class="body">
                        <table width="100%" cellspacing="0" cellpadding="0" class="tLight noBorderT">
                            <tbody>                             
                                <tr>
                                    <td width="200"><?php echo $this->translate('companylogo') ?></td>
                                     <td width="600"><img style="width: 80px; height:80px;"  src="<?php echo $this->baseUrl();?>/data/uploads/thumb/<?php echo $rows['Fou_Logo'];?>"/></td>
                                </tr>
                                <tr>
                                    <td width="200"><?php echo $this->translate('companyname')?></td>
                                    <td width="600"><?php echo $rows['Fou_Name'];?></td>
                                </tr>
                                <tr>
                                    <td width="200"><?php echo $this->translate('RaisonSocial')?></td>
                                    <td width="600"><?php echo $rows['Fou_RaisonSocial'];?></td>
                                </tr>
                                <tr>
                                   <td width="200"><?php echo $this->translate('companywebsite')?></td>
                                   <td width="600"><a href="http://<?php echo $rows['Fou_Website'];?>"><?php echo $rows['Fou_Website'];?></a></td>
                                </tr>
                                <tr>   
                                   <td width="200"><?php echo $this->translate('companyemail')?></td>
                                   <td width="600"><a href="mailto:<?php echo $rows['Fou_Mail'];?>"><?php echo $rows['Fou_Mail'];?></a></td> 
                                </tr>
                                <tr>
                                   <td width="200"><?php echo $this->translate('companycity')?></td>
                                    <td width="600"><?php echo $rows['Fou_City'];?></td>
                                </tr>
                                <tr>
                                    <td width="200"><?php echo $this->translate('companycountry')?></td>
                                    <td width="600"><?php echo $rows['Fou_Country'];?></td> 
                               </tr>
                                <tr>     
                                    <td width="200"><?php echo $this->translate('companyaddress1')?></td>
                                    <td width="600"><?php echo $rows['Fou_Adresse1'];?></td>   
                                </tr>
                                
                            </tbody>
                        </table>
                        
                        </div>
                    </div> 
                    
                    <!-- Map -->
                    <div class="widget justTable grid4">
                        <div class="body" align="center">
                                    <div class="body">
                                        <style>
                            		.map {
                            			height: 435px;
                            			width: 100%;
                            		}
                            		.ui-dialog
                            		{
                            			background:#fff;
                            			border:1px solid #ddd;
                            			padding:5px;
                            		}
                            		.ui-dialog-content {height:10px!important;}
                            		</style>
                                    <script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/modernizr.min.js"></script>
                                    <div id="map_canvas" class="map rounded"></div>
                                    <div id="dialog"></div>
                                    
                                    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>  
                                                               		
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/underscore-1.2.2/underscore.min.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/backbone-0.5.3/backbone.min.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/prettify/prettify.min.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/demo.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/jquery.ui.map.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/jquery.ui.map.services.js"></script>
                            		<script type="text/javascript" src="<?php echo $this->baseUrl ()?>/data/gmap/js/jquery.ui.map.extensions.js"></script>
                            		<script type="text/javascript">
                                    <?PHP
                                            /* for Convert accented characters to their plain ascii equivalents By Socheat Ngann */
                                    $normalizeChars = array(
                                        'Š'=>'S', 'š'=>'s', 'Ð'=>'Dj','Ž'=>'Z', 'ž'=>'z', 'À'=>'A', 'Á'=>'A', 'Â'=>'A', 'Ã'=>'A', 'Ä'=>'A',
                                        'Å'=>'A', 'Æ'=>'A', 'Ç'=>'C', 'È'=>'E', 'É'=>'E', 'Ê'=>'E', 'Ë'=>'E', 'Ì'=>'I', 'Í'=>'I', 'Î'=>'I',
                                        'Ï'=>'I', 'Ñ'=>'N', 'Ò'=>'O', 'Ó'=>'O', 'Ô'=>'O', 'Õ'=>'O', 'Ö'=>'O', 'Ø'=>'O', 'Ù'=>'U', 'Ú'=>'U',
                                        'Û'=>'U', 'Ü'=>'U', 'Ý'=>'Y', 'Þ'=>'B', 'ß'=>'Ss','à'=>'a', 'á'=>'a', 'â'=>'a', 'ã'=>'a', 'ä'=>'a',
                                        'å'=>'a', 'æ'=>'a', 'ç'=>'c', 'è'=>'e', 'é'=>'e', 'ê'=>'e', 'ë'=>'e', 'ì'=>'i', 'í'=>'i', 'î'=>'i',
                                        'ï'=>'i', 'ð'=>'o', 'ñ'=>'n', 'ò'=>'o', 'ó'=>'o', 'ô'=>'o', 'õ'=>'o', 'ö'=>'o', 'ø'=>'o', 'ù'=>'u',
                                        'ú'=>'u', 'û'=>'u', 'ý'=>'y', 'ý'=>'y', 'þ'=>'b', 'ÿ'=>'y', 'ƒ'=>'f'
                                    );                                   
                                        if($rows['Fou_Adresse1']!='')
                                        {
                                            //$address    = str_replace(' ', '%20', $Values['Com_City'].', '.$Values['Com_Address1']);
                                            $address    = str_replace(" ","+",$rows['Fou_Adresse1']) . ",+" . str_replace(" ","+",$rows['Fou_City']) . ",+" . str_replace(" ","+",$rows['Fou_Country']);
                                            $address    = strtr($address, $normalizeChars);
                                              /*Query Google Geocoding API */
                                            $ch = curl_init();
                                            curl_setopt($ch, CURLOPT_URL, "http://maps.googleapis.com/maps/api/geocode/xml?address=".$address."&sensor=false");
                                            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
                                            $xml = curl_exec($ch);                                                                                        
                                            
                                            //Use SimpleXML library to get the data from the XML string
                                            $xml = new SimpleXMLElement($xml);
                                            $lat = $xml->result[0]->geometry[0]->location[0]->lat;
                                            $lng = $xml->result[0]->geometry[0]->location[0]->lng;
                                            $coords = $lat . "," . $lng;
                                            curl_close($ch); //Close the CURL instance, to keep things tidy                                           
                                            if(!empty($lat)) {                                       
                                        ?>
                                        function initialize() {
                                   		    var latlng = new google.maps.LatLng(<?php echo $lat;?>, <?php echo $lng;?>);
                                            var myOptions = {
                                              zoom: 14,
                                              center: latlng,
                                              mapTypeId: google.maps.MapTypeId.ROADMAP
                                            };
                                            var map = new google.maps.Map(document.getElementById("map_canvas"),myOptions);
                                         
                                            var marker = new google.maps.Marker({
                                              position: latlng, 
                                              map: map, 
                                              title:""
                                            });
                                    	}  
                                            <?php }
                                            }
                                            ?>                                     	
                                    </script> 
                                    </div>
                        </div>
                    </div>   
                     
                    <!-- end Map -->
                     <div class="widget justTable grid4">
                        <div class="body" align="center">
                            <table width="100%" cellspacing="0" cellpadding="0" class="tLight noBorderT">
                         
                            <tbody>
                                <tr>
                                    <td><?php echo $this->translate('companytelephone')?></td>
                                    <td><?php echo $rows['Fou_Telephone'];?></td>
                                 </tr>
                                <tr>   
                                    <td><?php echo $this->translate('companyfax')?></td>
                                    <td><?php echo $rows['Fou_Fax'];?></td>
                                    
                                </tr>
                                <tr>
                                   <td width="200"><?php echo $this->translate('companycodepostal')?></td>
                                   <td width="600"><?php echo $rows['Fou_ZipCode'];?></td>
                                </tr>
                                <tr>   
                                   <td width="200"><?php echo $this->translate('companysiret')?></td>
                                   <td width="600"><?php echo $rows['Fou_Siret'];?></td> 
                                </tr>
                                <tr>
                                   <td width="200"><?php echo $this->translate('companystatus')?></td>
                                    <td width="600">
                                    <?php
                                    if($rows['Fou_Statut']=='Actif')
                                    {
                                        $ClassStatut = 'label-success';
                                    }
                                    else if($rows['Fou_Statut']=='Suspendu')
                                    {
                                        $ClassStatut = 'label-warning';
                                    }
                                    else if($rows['Fou_Statut']=='Inactif')
                                    {
                                        $ClassStatut = 'label-important';
                                    }
                                    else
                                    {
                                       $ClassStatut = ''; 
                                    }
                                    ?><span class="label <?php echo $ClassStatut;?>"><?php echo $rows['Fou_Statut'];?></span></td>
                                </tr>
                                <tr>
                                    <td width="200"><?php echo $this->translate('typefactory')?></td>
                                    <td width="600"><?php echo $rows['Fou_Type'];?></td> 
                               </tr>
                                <tr>
                                    <td width="200"><?php echo $this->translate('codefactory')?></td>
                                    <td width="600"><?php echo $rows['Fou_Refcode'];?></td> 
                               </tr>
                               <tr>
                                    <td width="200"><?php echo $this->translate('createdate')?></td>
                                    <td width="600"><?php echo $rows['Fou_createdate'];?></td> 
                               </tr>
                                 <tr>
                                    <td width="200"><?php echo $this->translate('modifydate')?></td>
                                    <td width="600"><?php echo $rows['Fou_modifdate'];?></td> 
                               </tr>
                            </tbody>
                        </table>
                        </div>
                    </div>
                    <!-- Photo Gallary -->
                    <!-- end Photo Gallary -->
                    
                </div>
               <div class="clear"></div>
                </div>	
                <div class="clear"></div>		 
            </div>  
                         
        </div>
    </div>
</div>
<?php 

                                endforeach;
                                endif;
                                ?>