<?php
    $javascript ='';
    $cssScript = '';
    $pageTitle = 'Mainternance';
    $content = $this->controller.'/'.$this->action.'.phtml';
    $breadLinks = '<ul><li><a title="" href="'.$this->baseUrl ().'/'.$this->translate('lang').'/'.$this->controller.'/add"><i class="icos-add"></i><span>'.$this->translate('create').'</span><strong></strong></a></li></ul>';
    require_once TMP_USER_PATH;
?>
<div id="contentdata">
	<div class="wrapper">
        <div class="fluid">
            <div class="widget grid12">
                <div class="whead"><h6>Grid6</h6><div class="clear"></div></div>
                <div class="body">class="grid6"</div>
            </div>
        </div>
        <!-- end <div class="fluid"> -->		
    </div>
    <!-- end <div class="wrapper"> -->
</div>
<!-- end <div id="contentdata"> -->