
<?php
$javascript = '';
$cssScript = '';
$pageTitle = 'Equipement';
$cssScript = '<style>.formRow{padding: 5px 16px;}#main8 .widget{margin-top: 15px;}</style>';
$content = $this->controller . '/' . $this->action . '.phtml';
$breadLinks = '<ul><li><a title="" href="'.$this->baseUrl ().'/'.$this->translate('lang').'/'.$this->controller.'/add"><i class="icos-add"></i><span>'.$this->translate('create').'</span><strong></strong></a></li></ul>';
require_once TMP_USER_PATH;
?>

<script type="text/javascript">
	$(document).ready(function(){
	    $("#research").hide();
        $("#basic_search").show();
	$('#advancedsearch').click(function(){
    $("#basic_search").hide();
	$("#research").slideToggle();
	$("#research").show();
	$("#basicsearch").click(function(){
		 $("#research").hide();
         $("#basic_search").show();
		});
	});
});
</script>
<div id="contentdata">
	<div class="wrapper">
			<div class="tab_container">
			<div id="search" class="tab_content">
			<form  action="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/index/">
			<div class="widget fluid">
                    <div class="body">
                      
					   <div id="basic_search">
                           <div class="formRow">                        
        						<div class="grid1">
        							<label><?php echo $this->translate('companyname')?>&nbsp;&nbsp;<b>:</b>
        							</label>
        						</div>
        						<div class="grid3">
        							<input type="text" name="txtnamebasic" />
        						</div>
        						<div class="grid8">
        							<input type="submit" class="buttonM bDefault" name="btnsearchBasic" value="<?php echo $this->translate('search')?>"/>
                                <input type="reset"  value="<?php echo $this->translate('reset')?>" class="buttonM bDefault"/>
    							&nbsp;&nbsp;<a href="#"><span id="advancedsearch"><?php echo $this->translate('advancesearch')?></span></a>
        						</div>
        						<div class="clear"></div>
                            </div>
                        </div>
                      
					</div>
					<div id="research">
						<div class="formRow fluid noBorderB">
							<div class="grid6">
								<div class="formRow fluid noBorderB">
			                        <div class="grid6"><label><?php echo $this->translate('companyname')?>: </label></div>
			                        <div class="grid6"><input type="text" value="" name="txtname" /></div>
			                        <div class="clear"></div>
		             			</div>
		             			<div class="formRow fluid noBorderB">
			                         <div class="grid6"><label><?php //echo $this->translate('companyaddress1')?>Fournisseur:</label></div>
	                        		<div class="grid6"><input type="text" value="" name="txtTournisseur" /></div>
			                        <div class="clear"></div>
		             			</div> 
							</div>
							<div class="grid6">
								<div class="formRow fluid noBorderB">
			                         <div class="grid4"><label><?php //echo $this->translate('companycountry')?>Reference: </label></div>
	                        		<div class="grid6"><input type="text" value="" name="txtReference" /></div>
			                        <div class="clear"></div>
		             			</div>
		             			<div class="formRow fluid noBorderB">
			                         <div class="grid4"><label><?php //echo $this->translate('companytelephone')?>Date commissioning: </label></div>
	                        		<div class="grid6"><input class="datepicker" type="text" value="" name="txtDateCommiss" /></div>
			                        <div class="clear"></div>
		             			</div>
		             			<div class="formRow fluid noBorderB">
			                         <div class="grid4"><label><?php //echo $this->translate('mobilephone')?>Date of manufacture: </label></div>
	                        		<div class="grid6"><input class="datepicker" type="text" value="" name="txtDateManufacture" /></div>
			                        <div class="clear"></div>
		             			</div>
		             			<div class="formRow fluid noBorderB">
			                <a href="#"><span id="basicsearch"><?php echo $this->translate('basicsearch')?></span></a>&nbsp;&nbsp;&nbsp;         
                            <input class="buttonM bRed" type="reset" value="<?php echo $this->translate('reset')?>" />
                            <input class="buttonM bBlue" type="submit" value="<?php echo $this->translate('search')?>" name="btnAdvanceSearch" />
			                        <div class="clear"></div>
		             			</div>
							</div>
						</div>	

						<div class="formRow">
                        <div class="status" id="status3"></div>
                        <div class="formSubmit">
                        	
                            <div class="clear"></div>
                        </div>
                        <div class="clear"></div>
               </div>

					</div>  
			</div>
			</form>
			
               <form method="post"
			action="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/delete"
			id="SiteForm" name="SiteForm">
				<!-- result content -->
				<div class="widget check">
					<div class="whead">
						<span class="titleIcon"> <input type="checkbox" id="titleCheck"
							name="titleCheck" />
						</span>
						<h6><?php echo $this->translate('viewsite')?></h6>
						<div class="clear"></div>
					</div>
					
                    <div id="dyn2" class="shownpars">                        
					<table cellpadding="0" cellspacing="0" width="100%"
						class="dTable tDefault checkAll tMedia" id="checkAll">
						<thead>

							<tr>
								<td><img src="<?php echo $this->baseUrl();?>/images/elements/other/tableArrows.png" alt="" /></td>
								<!--
<td width="100"><?php //echo $this->translate('edit')?></td>
-->
								<td class="sortCol" width="150"><div>
										N<sup>o</sup>&nbsp;&nbsp;<?php echo $this->translate('reference')?><span></span>
									</div></td>
								<td class="sortCol" width="150"><div>
										<?php echo $this->translate('companyname')?><span></span>
									</div>
								</td>
					
								<td class="sortCol">
									<div>Description:<?php //echo $this->translate('reference')?><span></span></div>
								</td>
								<td class="sortCol">
									<div>Site<span></span></div>
								</td>
								<td class="sortCol">
								<div><?php echo $this->translate('datecommision')?><span></span></div></td>
								<td class="sortCol"><div><?php echo $this->translate('datemenufacture')?><span></span>
									</div></td>									
									<!--
<td class="sortCol"><div>
										<?php echo $this->translate('siteacontroler')?><span></span>
									</div></td>
-->
								<td width="100">Actions</td>
							</tr>
						</thead>
						<tfoot>
							<tr>
								<td colspan="8">
									<div class="itemActions">										
										<select id="actionSelect" name="multiAction">
											<option value="">---- <?php echo $this->translate('selectone')?> ----</option>
											<option value="delete"><?php echo $this->translate('delete')?></option>
										</select>
									</div>
									<input onclick="return confirm('<?php echo $this->translate('areyousure') ?>')" style="margin-top: 6px; margin-left: 5px; height: 28px;" class="tablectrl_medium bDefault" type="submit"  value="<?php echo $this->translate('apply')?>" name="btnDeleteMulti" />

	   				
								</td>
								
							</tr>
						
						</tfoot>
						
						<tbody>
                         <?php 
								if(count($this->getAllCategoryMaintenace)!=0){
									foreach ($this->getAllCategoryMaintenace as $getCategoryMaintenance){
						?> 
	   				    <tr class="row<?php echo $getCategoryMaintenance['catmain_id']?>">
	   					<td><input type="checkbox" name="checkRow[]" value="<?php echo $getCategoryMaintenance['catmain_id'];?>" /></td>
		                </td>
	   					<td>000<?php echo $getCategoryMaintenance['catmain_id'];?></td>	
	   					<td><a href="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/overview?actions=overview&&id=<?php echo $getCategoryMaintenance['catmain_id']; ?>"><?php echo $getCategoryMaintenance['catmain_name'];?></a></td>
	   					<td><a href="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/overview?actions=overview&&id=<?php echo $getCategoryMaintenance['catmain_id']; ?>"><?php echo $getCategoryMaintenance['catmain_description'];?></a></td>
	   					<td><?php echo $getCategoryMaintenance['catmain_description'];?></td>
	   					
	   					<td><?php //echo $getCategoryMaintenance['catmain_description'];?></td>
	   					<td><?php //echo $getCategoryMaintenance['catmain_description'];?></td>
	   					<td class="tableActs noBorderB" align="center">
                            <a href="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/edit?actions=edit&&id=<?php echo $getCategoryMaintenance['catmain_id'];?>" class="tablectrl_small bBlue tipS" original-title="<?php echo $this->translate('edit')?>"><span class="iconb" data-icon="&#xe1db;"></span></a>
                            <a href="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/delete?actions=delete&&id=<?php echo $getCategoryMaintenance['catmain_id'];?>" class="tablectrl_small bRed tipS" original-title="<?php echo $this->translate('remove')?>" onclick="return confirm('<?php echo $this->translate('areyousure') ?>')"><span class="iconb" data-icon="&#xe136;"></span></a>
                            
                        </td>
	   				</tr>
	   				<?php 
	   					}
	   				}
 					?>
					</tbody>
					
						</table>
                        
				</div>
				</form>
				<!-- end result content -->
			</div>
			<!-- end search content -->
	   </div>
	<div class="clear"></div>
	
</div>
</div>