<?php
    $javascript ='';
    $cssScript = '';
    $pageTitle = $this->translate('edit');
    $cssScript = '<style>.formRow{padding: 5px 16px;}#main8 .widget{margin-top: 15px;}
    .marinright{margin-right:50px;}
    #addfield, .removerow, .cusors {cursor:pointer;cursor:hand}
    </style>';
	$content = $this->controller.'/'.$this->action.'.phtml';
    require_once TMP_USER_PATH;
?>
<div id="contentdata">
<form name="registerForm"  enctype="multipart/form-data" id="usualValidate" class="main" method="post" action="<?php echo $this->baseUrl ();?>/<?php echo $this->translate('lang')?>/<?php echo $this->controller?>/add">
    <div class="wrapper">	
	   <div class="fluid">
                <div class="widget grid12">       
                    <ul class="tabs">
                        <li class="tabl1"><a href="#tabb1"><?php echo $this->translate('categorymanagent')?></a></li>
                        <li class="tabl2"><a href="#tabb2"><?php echo $this->translate('maintenance')?></a></li>
                        <li class="tabl3"><a href="#tabb3"><?php echo $this->translate('referencecode')?></a></li>
                    </ul>
                    
                    <div class="tab_container">
                        <div id="tabb1" class="tab_content">
                            <div id="main12">
                            <!-- main grid8 -->
            					<div class="grid12">                       
                                        <div class="formRow fluid">
                							<div class="grid4">
                								<label>Category Name<?php //echo $this->translate('companyname')?>:<span class="req">*</span></label>
                							</div>
                							<div class="grid8">
                								<input type="text" value="" name="txtCatMaintenanceName"  id="txtCatMaintenanceName" class="required"/>
                                                  <label for="txtCatMaintenanceName" class="error txtCatMaintenanceNameLabel" style="display: none;"><?php echo $this->translate('requiredfile')?></label>
                							</div>							
                							<div class="clear"></div>
                						</div>
                						
                						<div class="formRow fluid">
                							<div class="grid4">
                								<label>Description<?php //echo $this->translate('RaisonSocial')?>:<span class="req"></span></label>
                							</div>
                							<div class="grid8">
                								<input type="text" value="" name="txtDescription" id="txtDescription" />
                							</div>
                						<div class="clear"></div>
                						</div>      

                                   <!--The end grid 6-->   
                                        <!-- end  conent tab1 -->
                                        <div class="clear"></div>
                                        <div class="formRow fluid"><div class="clear"></div> </div>
                                </div>
                            </div>            
                        </div>
                        
                        
                        <div id="tabb2" class="tab_content"> 
                        	<div id="main12">
                                <!-- main grid8 -->
            					<div class="grid12">                        
                                        <!-- form inside -->
                                        <div class="formRow">
            		                        <div class="grid4"><label>Maintenance Name:<span class="req">*</span></label></div>
            		                        <div class="grid6"><input type="text" value="" name="txtmaintenance" id="txtmaintenance" class="required" />
                                            <label for="txtmaintenance" class="error txtmaintenanceLabel" style="display: none;"><?php echo $this->translate('requiredfile')?></label>
                                          
                                            </div>
            		                        <div class="clear"></div>
                         			    </div>
                                        
                                        <div class="formRow">
            		                        <div class="grid4"><label>Description:<span class="req"></span></label></div>
            		                        <div class="grid6"><textarea name="txtdescription"></textarea></div>
            		                        <div class="clear"></div>
                         			    </div>
                                        
                                        
                         			     
                                        <div class="formRow">
            		                        <div class="grid4"><label>Maintenance Usage:</label></div>
            		                        <div class="grid6">
            		                        	<select name="cmbomaintenaceusage" id="users_title">
            										<option value="">---- <?php echo $this->translate('selectone')?> ----</option>
            										<option value="">A</option>
            										<option value="">B</option>
            									</select>
                                                <!--<label for="users_title" class="error users_titleLabel" style="display: none;"><?php //echo $this->translate('requiredfile')?></label>-->
            		                        </div><div class="clear"></div>
                         			    </div>
                                        
                                          
                                        <div class="formRow">
            		                        <div class="grid4"><label>Maintenance Type:</label></div>
            		                        <div class="grid6">
            		                        	<select name="cmbomaintenaceusage" id="users_title">
            										<option value="">---- <?php echo $this->translate('selectone')?> ----</option>
            										<option value="">A</option>
            										<option value="">B</option>
            									</select>
                                                <!--<label for="users_title" class="error users_titleLabel" style="display: none;"><?php //echo $this->translate('requiredfile')?></label>-->
            		                        </div><div class="clear"></div>
                         			    </div>
                                        <!-- end inside tab2 -->
                                </div>
                            </div>  
                        </div>
                       <!-- end tab2 --> 
                        
                        <div id="tabb3" class="tab_content"> 
                        	<div id="main12">
                                <!-- main grid8 -->
            					<div class="grid12">                        
                                        <!-- form inside -->
                                        <div class="formRow fluid">
                                            <div class="grid11">
                                                <div class="grid3">
                        							<label><?php echo $this->translate('orderby')?>:</label>                        							
                                                </div>
                                                <div class="grid3">
                                                    <label><?php echo $this->translate('code')?>:</label>                                                    
                                                </div>
                                                <div class="grid3">
                    								<label><?php echo $this->translate('label')?>:</label>                                                    
                    							</div>
                                                <div class="grid3">
                    								<label><?php echo $this->translate('description')?>:</label>                                                   
                    							</div>
                    							<div class="clear"></div>
                    						</div>
                                            <div class="grid1">
                                                <div id="addfield" class="tablectrl_small bDefault"><span class="iconb" data-icon="&#xe14a;"></span></div>
                                                
                                            </div>
                                        </div>
                                        
                                        <div id="morefield">                                        
                                        <div class="formRow fluid">
                                        
                                            <div class="grid11">
                                                <div class="grid3">
                        							<input type="text" value="" name="txtOrderby"  id="txtOrderby" class=""/>
                                                </div>
                                                <div class="grid3">
                                                    <input type="text" value="" name="txtCode"  id="txtCode" class=""/>
                                                </div>
                                                <div class="grid3">
                    								<input type="text" value="" name="txtLabel"  id="txtLabel" class=""/>
                    							</div>
                                                <div class="grid3">
                                                    <textarea placeholder="Your message"  name="txtDescription"  id="txtDescription" cols="" rows="1"></textarea>
                    							</div>
                    							<div class="clear"></div>
                    						</div>
                                            <div class="grid1">
                                                
                                            </div>
                                        </div>
                                        </div>
                                        <div class="clear"></div>
                                        <!-- end content tab3 -->
                                </div>
                            </div>  
                        </div>
                       <!-- end tab3 --> 
                    </div>	
                    <div class="clear"></div>		 
                </div>
                <div class="clear"></div>
                <div class="formRow">
                    <div class="body">
                    <br/>
                         <a class="buttonS bGreyish" href="<?php echo  $this->url(array('Controller'=>'organisme','action'=>'index'));?>"><?php echo $this->translate('cancel')?></a>&nbsp;&nbsp;&nbsp;
                        <input class="buttonM bRed" id="back3" value="<?php echo $this->translate('reset')?>" type="reset" />
                        <input style="display: none;" id="back1" class="cusors buttonM bDefault ml10" value="<?php echo $this->translate('back')?>" type="button"/>
                        <input style="display: none;" id="back2" class="cusors buttonM bDefault ml10" value="<?php echo $this->translate('back')?>" type="button"/>
                        <input id="next2" class="cusors buttonM bDefault ml10" value="<?php echo $this->translate('next')?>" type="button"/>
                        <input style="display: none;" id="next3" class="cusors buttonM bDefault ml10" value="<?php echo $this->translate('next')?>" type="button"/>
            			<input id="submitform" style="display: none;" class="buttonM bBlue ml10" name="SaveOrg" value="<?php echo $this->translate('submit')?>" type="submit"/>
                        
                    </div>
                 </div>				
            </div>
        </div>
        </form>
    </div>
	
<script>
$(document).ready(function(){

  $("#addfield").click(function(){
    $("#morefield").append('<ul><li><div id="idremove" class="formRow fluid"><div class="grid11"><div class="grid3"><input type="text" value="" name="txtOrderby"  id="txtOrderby" class=""/></div><div class="grid3"><input type="text" value="" name="txtCode"  id="txtCode" class=""/></div><div class="grid3"><input type="text" value="" name="txtLabel"  id="txtLabel" class=""/></div><div class="grid3"><textarea placeholder="Your message"  name="txtDescription"  id="txtDescription" cols="" rows="1"></textarea></div><div class="clear"></div></div><div class="grid1"><div class="removerow tablectrl_small bDefault"><span class="iconb" data-icon="&#xe14c;"></span></div></div></div></li></ul>');
  });
 
$("ul li .removerow").live("click", function() {  
         $(this).parent().parent().remove();
  });
    $("#next2").click(function()
    {
            var txtName=$("#txtCatMaintenanceName").val();
            if (txtName==null || txtName=="")
            {
                $('.txtCatMaintenanceNameLabel').show();
                return false;
            } 
        $(".tabl1").removeClass("activeTab");
        $(".tabl2").addClass("activeTab");
        $("#back1").show();
        $("#next3").show();
        $("#next2").hide();
        $("#tabb1").hide();
        $("#tabb2").show();
        $("#tabb3").hide();
        $("#submitform").hide();
    });
    $("#next3").click(function()
    {
        var txtmaintenance=$("#txtmaintenance").val();
            if (txtmaintenance==null || txtmaintenance==""){
                $('.txtmaintenanceLabel').show();
                return false;
            } else{
        $(".tabl2").removeClass("activeTab");
        $(".tabl3").addClass("activeTab");
        $("#back2").show();
        $("#back1").hide();
        $("#next3").hide();
        $("#next2").hide();
        $("#tabb1").hide();
        $("#tabb2").hide();
        $("#tabb3").show();
        $("#submitform").show();
        }
    });
    
    $(".tabl1").click(function()
    {
        $(".tabl2").removeClass("activeTab");
        $(".tabl1").addClass("activeTab");
        $("#back1").hide();
        $("#next3").hide();
        $("#next2").show();
        $("#submitform").hide();
    });
    $(".tabl2").click(function()
    {
         var txtmaintenanc=$("#txtmaintenance").val();
            if (txtmaintenanc==null || txtmaintenanc==""){
                $('.txtmaintenanceLabel').show();
                return false;
        }else{
        $(".tabl1").removeClass("activeTab");
        $(".tabl2").addClass("activeTab");
        $("#back1").show();
        $("#back2").hide();
        $("#next3").show();
        $("#next2").hide();
        $("#submitform").hide();
        }
    });
    $(".tabl3").click(function()
    {
        var txtmaintenanc=$("#txtmaintenance").val();
            if (txtmaintenanc==null || txtmaintenanc==""){
                $('.txtmaintenanceLabel').show();
                return false;
        }else{
        $(".tabl2").removeClass("activeTab");
        $(".tabl3").addClass("activeTab");
        $("#back2").show();
        $("#back1").hide();
        $("#next3").hide();
        $("#next2").hide();
        $("#submitform").show();
        }
    });
    
    

  $("#back1").click(function()
    {
        $(".tabl2").removeClass("activeTab");
        $(".tabl1").addClass("activeTab");
        $("#back1").hide();
        $("#next3").hide();
        $("#next2").show();
        $("#tabb1").show();
        $("#tabb2").hide();
        $("#tabb3").hide();
        $("#submitform").hide();
    }); 
    
    $("#back2").click(function()
    {
        $(".tabl3").removeClass("activeTab");
        $(".tabl2").addClass("activeTab");
        $("#back1").show();
        $("#next3").show();
        $("#next2").hide();
        $("#back2").hide();
        $("#tabb1").hide();
        $("#tabb2").show();
        $("#tabb3").hide();
        $("#submitform").hide();
    });
});
 
</script>   

 
