
<div class="navbar">
	<div class="navbar-inner">

		<div class="container-fluid">
			<a href="<?php echo $this->baseUrl();?>/" title="" class="logo">
			<img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="" /></a>
			<!-- <a
				href="<?php echo $this->url(array('controller'=>'index','action'=>'register','lang'=>$this->translate('lang')));?>"
				class="btn btn-primary pull-right"><?php echo $this->translate('register');?></a> -->
		</div>
	</div>
</div>
<!-- Top line begins -->
<div id="top">
	<div class="wrapper">
    	<<a href="<?php echo $this->baseUrl();?>/" title="" class="logo"><img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="" /></a>
        
        <!-- Right top nav -->
        <div class="topNav">
            <ul class="userNav">
                <li><a href="#" title="" class="screen"></a></li>
                <li><a href="#" title="" class="settings"></a></li>
                <li><a href="#" title="" class="logout"></a></li>
            </ul>
        </div>
        <div class="clear"></div>
    </div>
</div>
<!-- Top line ends -->
