	<!--	<div class="contentTop">
		<span class="pageTitle"><i class="icon-dashboard"></i><?php echo $this->translate('home')?></span>
		<ul class="quickStats">
			<li><a href="./index.html" class="blueImg"><img
					src="<?php echo $this->baseUrl();?>/images/icons/quickstats/admin.png"
					alt="" /></a>
				<div class="floatR margin-top9">
					<strong class="blue"><a href="./index.html"><?php echo $this->translate('admin')?></a></strong>
				</div></li>
			<li><a href="./index.html" class="blueImg"><img
					src="<?php echo $this->baseUrl();?>/images/icons/quickstats/support.png"
					alt="" /></a>
				<div class="floatR margin-top9">
					<strong class="blue"><a href="./index.html"><?php echo $this->translate('support')?></a></strong>
				</div></li>
			<li><a href="./index.html" class="blueImg"><img
					src="<?php echo $this->baseUrl();?>/images/icons/quickstats/employee.png"
					alt="" /></a>
				<div class="floatR margin-top9">
					<strong class="blue"><a href="./index.html"><?php echo $this->translate('employee')?></a></strong>
				</div></li>
		</ul>
		<div class="clear"></div>
	</div>
  -->