<div id="sidebar">
	<div class="mainNav">
		<div class="user">

			<a title="" class="leftUserDrop">               
      <?php
						// foreach ( $this->getResultProfile as $values ) {
						?>
          <img
				src="<?php //echo $this->baseUrl().'/data/uploads/thumb/'.$values['Com_Logo']; ?>" />
			</a> <span>    
       <?php
							// }
							// session_start();
							if ($_SESSION ['UserSession']) {
								echo $_SESSION ['UserSession'];
							}
							?> 
</span>
			<ul class="leftUser">
				<li><a href="#" title="" class="sProfile">My profile </a></li>
				<li><a href="#" title="" class="sMessages">Messages </a></li>
				<li><a href="#" title="" class="sSettings">Settings </a></li>
				<li><a href="#" title="" class="sLogout">Logout </a></li>
			</ul>
		</div>

		<!-- Responsive nav -->
		<div class="altNav">
			<div class="userSearch">
				<form action="">
					<input type="text" placeholder="search..." name="userSearch" /> <input
						type="submit" value="" />
				</form>
			</div>

			<!-- User nav -->
			<ul class="userNav">
				<li><a href="#" title="" class="profile"></a></li>
				<li><a href="#" title="" class="messages"></a></li>
				<li><a href="#" title="" class="settings"></a></li>
				<li><a href="#" title="" class="logout"></a></li>
			</ul>
		</div>

		<!-- Main nav -->
		<ul class="nav">
			<li><a href="./index.html" title=""><img
					src="<?php echo $this->baseUrl();?>/images/icons/mainnav/dashboard.png"
					alt="" /><span><?php echo $this->translate('home')?></span></a></li>
			<li><a
				href="<?php echo $this->url(array('controller'=>'Organisme','action'=>'index','lang'=>$this->translate('lang')));?>"
				title=""><img
					src="<?php echo $this->baseUrl();?>/images/icons/mainnav/organisme.png"
					alt="" /><span>Organisme</span></a></li>
			<!-- <li><a href="./forms.html" title=""><img src="<?php echo $this->baseUrl();?>/images/icons/mainnav/forms.png" alt="" /><span>Fourmisseur</span></a>
                 <ul>
                     <li><a href="./forms.html" title=""><span class="icol-list"></span>Inputs &amp; xxxxxxxx </a></li>
                     <li><a href="./form_validation.html" title=""><span class="icol-alert"></span>Validation </a></li>
                     <li><a href="./form_editor.html" title=""><span class="icol-pencil"></span>File uploader &amp; WYSIWYG </a></li>
                     <li><a href="./form_wizards.html" title=""><span class="icol-signpost"></span>Form wizards </a></li>
                 </ul>
             </li> -->
			<li><a href="./messages.html" title=""><img
					src="<?php echo $this->baseUrl();?>/images/icons/mainnav/site.png"
					alt="" /><span>Site</span></a></li>
			<li><a href="./statistics.html" title=""><img
					src="<?php echo $this->baseUrl();?>/images/icons/mainnav/type.png"
					alt="" /><span>Type equipement</span></a></li>
			<li><a href="./tables.html" title=""><img
					src="<?php echo $this->baseUrl();?>/images/icons/mainnav/equip.png"
					alt="" /><span>Equipement</span></a>
				<ul>
					<li><a href="./tables.html" title=""><span class="icol-frames"></span>Standard
							tables </a></li>
					<li><a href="./tables_dynamic.html" title=""><span
							class="icol-refresh"></span>Dynamic table </a></li>
					<li><a href="./tables_control.html" title=""><span
							class="icol-bullseye"></span>Tables with xxxxxxx </a></li>
					<li><a href="./tables_sortable.html" title=""><span
							class="icol-transfer"></span>Sortable and xxxxxxxxx </a></li>
				</ul></li>
			<!--  <li><a href="./other_calendar.html" title=""><img src="<?php echo $this->baseUrl();?>/images/icons/mainnav/other.png" alt="" /><span>Gestionnaire</span></a>
                 <ul>
                     <li><a href="./other_calendar.html" title=""><span class="icol-dcalendar"></span>Calendar </a></li>
                     <li><a href="./other_gallery.html" title=""><span class="icol-images2"></span>Images gallery </a></li>
                     <li><a href="./other_file_manager.html" title=""><span class="icol-files"></span>File manager </a></li>
                     <li><a href="#" title="" class="exp"><span class="icol-alert"></span>Error pages  <span class="dataNumRed">6 </span></a>
                         <ul>
                             <li><a href="./other_403.html" title="">403 error </a></li>
                             <li><a href="./other_404.html" title="">404 error </a></li>
                             <li><a href="./other_405.html" title="">405 error </a></li>
                             <li><a href="./other_500.html" title="">500 error </a></li>
                             <li><a href="./other_503.html" title="">503 error </a></li>
                             <li><a href="./other_offline.html" title="">Website is xxxxxxx error </a></li>
                         </ul>
                     </li>
                     <li><a href="./other_typography.html" title=""><span class="icol-create"></span>Typography </a></li>
                     <li><a href="./other_invoice.html" title=""><span class="icol-money2"></span>Invoice template </a></li>
                 </ul>
             </li>-->
		</ul>
	</div>


	<!-- Secondary nav -->
	<div class="secNav">
		<div class="secWrapper">
			<div class="secTop">
	
				<div class="balance">
					<div class="balInfo">Dashboad</div>

				</div>
				<a href="#" class="triangle-red"></a>
			</div>

			
			<!-- Tabs container -->
			<div id="tab-container" class="tab-container">
				<ul class="iconsLine ic3 etabs" style="display: none">
					<li><a href="#general" title=""><span class="icos-fullscreen"></span></a></li>
					<li><a href="#alt1" title=""><span class="icos-user"></span></a></li>
					<li><a href="#alt2" title=""><span class="icos-archive"></span></a></li>
				</ul>



				<div id="general"></div>

				<div id="alt1"></div>


				<div id="alt2"></div>
			</div>
			<ul class="subNav">
				<li class="activeli"><a href="#" title="" class="this"><span class="icos-admin2"></span>Administrator</a></li>
				<li><a href="#" title=""><span	class="icos-settings2"></span>Support</a></li>
				<li><a href="#" title=""><span class="icos-users2"></span>Employee</a></li>
			</ul>

		</div>
		<div class="clear"></div>
	</div>
	<!--End Secondary nav -->

</div>